export const UI_TEXT = {
  en: {
    // NAV
    reader: "Reader",
    speak: "Speak",
    words: "Words",
    grammar: "Grammar Lens",
    calligraphy: "Calligraphy",
    getStarted: "Get Started",
    logout: "Log out",
    beta: "Beta",

    // AUTH UI
    authTitle: "Turn any text into a pronunciation lesson",
    authSubtitle: "Paste your text, split it into cards, listen, repeat, translate, and check grammar on demand.",
    welcomeBack: "Welcome back 👋",
    loginHint: "Log in or create an account to continue.",
    name: "Name",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    login: "Log in",
    createAccount: "Create account",
    enterEmail: "Enter your email",
    restorePassword: "Restore password",

    // AUTH / PASSWORD RESET
    createNewPassword: "Please create a new password.",
    passwordTooShort: "Password should be at least 6 characters.",
    savingPassword: "Saving new password...",

    // AUTH MESSAGES
    loggingIn: "Logging in...",
    creatingAccount: "Creating account...",
    enterAllFields: "Please enter name, email, and password.",
    enterEmailError: "Please enter your email.",
    enterEmailInstruction: "Enter your email and click Restore password.",
    sendingRecovery: "Sending password recovery email...",
    recoverySent: "Password recovery email sent. Please check your inbox.",
    accountCreated: "Account created. Please check your email, then log in.",
    signupFailed: "Signup failed. Please try again.",
    passwordUpdated: "Password updated.",

    // READER
    readerTitle: "Turn any text into a pronunciation lesson",
    yourText: "Your text",
    pasteHint: "Paste a text in the language you want to practice.",
    createCards: "Create cards",
    saveText: "Save text",
    savedTexts: "Saved texts",
    practiceCards: "Practice cards",
    practiceHint: "Listen, record, translate, and inspect grammar.",

    // FULL TEXT
    fullText: "Full Text",
    readComplete: "Read the complete imported text.",
    play: "🔊 Play",
    pause: "⏸ Pause",
    slowOff: "🐢 Slow: OFF",
    slowOn: "🐢 Slow: ON",
    translate: "🌐 Translate",
    showPinyin: "🔤 Show pinyin",
    checkGrammar: "🧠 Check grammar",

    // CARDS / GAME
    record: "🎤 Record",
    next: "Next →",
    previous: "← Previous",
    skip: "Skip",
    listening: "Listening...",
    tryAgain: "Try again",
    greatJob: "Great job!",

    heroText: "Paste your text, split it into cards, listen, repeat, translate, and check grammar on demand.",
    welcomeMagic: "Welcome to Magic Read",
    listenRepeat: "Listen & Repeat",
    perfectPronunciation: "Perfect your pronunciation",
    smartCards: "Smart Cards",
    studyInteractive: "Study with interactive cards",
    translateLearn: "Translate & Learn",
    understandEverySentence: "Understand every sentence",
    or: "or",

    howItWorks: "How it works",
    howTitle: "From any text to active language practice",

    savedTextsTitle: "Saved texts",
    inputPlaceholder: "Paste your text here...",
  },

  ru: {
    reader: "Чтение",
    speak: "Речь",
    words: "Слова",
    grammar: "Грамматика",
    calligraphy: "Письмо",
    getStarted: "Начать",
    logout: "Выйти",
    beta: "Бета",

    authTitle: "Превратите любой текст в урок произношения",
    authSubtitle: "Вставьте текст, разделите его на карточки, слушайте, повторяйте, переводите и изучайте грамматику.",
    welcomeBack: "С возвращением 👋",
    loginHint: "Войдите или создайте аккаунт, чтобы продолжить.",
    name: "Имя",
    email: "Email",
    password: "Пароль",
    forgotPassword: "Забыли пароль?",
    login: "Войти",
    createAccount: "Создать аккаунт",
    enterEmail: "Введите email",
    restorePassword: "Восстановить пароль",

    // RU
    createNewPassword: "Создайте новый пароль.",
    passwordTooShort: "Пароль должен содержать минимум 6 символов.",
    savingPassword: "Сохраняем новый пароль...",

    loggingIn: "Выполняется вход...",
    creatingAccount: "Создаём аккаунт...",
    enterAllFields: "Введите имя, email и пароль.",
    enterEmailError: "Введите email.",
    enterEmailInstruction: "Введите email и нажмите «Восстановить пароль».",
    sendingRecovery: "Отправляем письмо для восстановления...",
    recoverySent: "Письмо отправлено. Проверьте почту.",
    accountCreated: "Аккаунт создан. Проверьте почту и войдите.",
    signupFailed: "Ошибка регистрации. Попробуйте снова.",
    passwordUpdated: "Пароль обновлён.",

    readerTitle: "Превратите любой текст в урок произношения",
    yourText: "Ваш текст",
    pasteHint: "Вставьте текст на нужном языке.",
    createCards: "Создать карточки",
    saveText: "Сохранить текст",
    savedTexts: "Мои тексты",
    practiceCards: "Карточки",
    practiceHint: "Слушайте, записывайте, переводите и изучайте грамматику.",

    fullText: "Полный текст",
    readComplete: "Читайте весь текст целиком.",
    play: "🔊 Слушать",
    pause: "⏸ Пауза",
    slowOff: "🐢 Медленно: выкл.",
    slowOn: "🐢 Медленно: вкл.",
    translate: "🌐 Перевести",
    showPinyin: "🔤 Пиньинь",
    checkGrammar: "🧠 Грамматика",

    record: "🎤 Записать",
    next: "Далее →",
    previous: "← Назад",
    skip: "Пропустить",
    listening: "Слушаем...",
    tryAgain: "Попробуйте снова",
    greatJob: "Отлично!",

    heroText: "Paste your text, split it into cards, listen, repeat, translate, and check grammar on demand.",
    welcomeMagic: "Welcome to Magic Read",
    listenRepeat: "Listen & Repeat",
    perfectPronunciation: "Perfect your pronunciation",
    smartCards: "Smart Cards",
    studyInteractive: "Study with interactive cards",
    translateLearn: "Translate & Learn",
    understandEverySentence: "Understand every sentence",
    or: "or",

    howItWorks: "How it works",
    howTitle: "From any text to active language practice",

    savedTextsTitle: "Saved texts",
    inputPlaceholder: "Paste your text here...",
  },

  zh: {
    reader: "阅读",
    speak: "口语",
    words: "词卡",
    grammar: "语法",
    calligraphy: "书写",
    getStarted: "开始",
    logout: "退出",
    beta: "测试版",

    authTitle: "把任何文本变成发音练习课",
    authSubtitle: "粘贴文本，生成卡片，听、跟读、翻译并查看语法。",
    welcomeBack: "欢迎回来 👋",
    loginHint: "登录或创建账户继续。",
    name: "姓名",
    email: "邮箱",
    password: "密码",
    forgotPassword: "忘记密码？",
    login: "登录",
    createAccount: "创建账户",
    enterEmail: "请输入邮箱",
    restorePassword: "重置密码",

    // ZH
    createNewPassword: "请创建新密码。",
    passwordTooShort: "密码至少需要 6 个字符。",
    savingPassword: "正在保存新密码...",

    loggingIn: "正在登录...",
    creatingAccount: "正在创建账户...",
    enterAllFields: "请输入姓名、邮箱和密码。",
    enterEmailError: "请输入邮箱。",
    enterEmailInstruction: "请输入邮箱并点击“重置密码”。",
    sendingRecovery: "正在发送邮件...",
    recoverySent: "邮件已发送，请检查邮箱。",
    accountCreated: "账户已创建，请检查邮箱。",
    signupFailed: "注册失败，请重试。",
    passwordUpdated: "密码已更新。",

    readerTitle: "把任何文本变成发音练习课",
    yourText: "你的文本",
    pasteHint: "粘贴要练习的文本。",
    createCards: "生成卡片",
    saveText: "保存文本",
    savedTexts: "已保存文本",
    practiceCards: "练习卡片",
    practiceHint: "听、录音、翻译并查看语法。",

    fullText: "全文",
    readComplete: "阅读完整文本。",
    play: "🔊 播放",
    pause: "⏸ 暂停",
    slowOff: "🐢 慢速：关",
    slowOn: "🐢 慢速：开",
    translate: "🌐 翻译",
    showPinyin: "🔤 拼音",
    checkGrammar: "🧠 语法",

    record: "🎤 录音",
    next: "下一步 →",
    previous: "← 上一步",
    skip: "跳过",
    listening: "正在听...",
    tryAgain: "再试一次",
    greatJob: "很好！",

    heroText: "Paste your text, split it into cards, listen, repeat, translate, and check grammar on demand.",
    welcomeMagic: "Welcome to Magic Read",
    listenRepeat: "Listen & Repeat",
    perfectPronunciation: "Perfect your pronunciation",
    smartCards: "Smart Cards",
    studyInteractive: "Study with interactive cards",
    translateLearn: "Translate & Learn",
    understandEverySentence: "Understand every sentence",
    or: "or",

    howItWorks: "How it works",
    howTitle: "From any text to active language practice",

    savedTextsTitle: "Saved texts",
    inputPlaceholder: "Paste your text here...",
  },

  tr: {
    reader: "Okuma",
    speak: "Konuşma",
    words: "Kelimeler",
    grammar: "Dilbilgisi",
    calligraphy: "Yazı",
    getStarted: "Başla",
    logout: "Çıkış yap",
    beta: "Beta",

    authTitle: "Her metni telaffuz dersine dönüştür",
    authSubtitle: "Metni yapıştır, kartlara böl, dinle, tekrar et, çevir ve dilbilgisini incele.",
    welcomeBack: "Tekrar hoş geldin 👋",
    loginHint: "Devam etmek için giriş yap veya hesap oluştur.",
    name: "Ad",
    email: "E-posta",
    password: "Şifre",
    forgotPassword: "Şifremi unuttum",
    login: "Giriş yap",
    createAccount: "Hesap oluştur",
    enterEmail: "E-posta gir",
    restorePassword: "Şifreyi sıfırla",

    // TR
    createNewPassword: "Lütfen yeni bir şifre oluştur.",
    passwordTooShort: "Şifre en az 6 karakter olmalı.",
    savingPassword: "Yeni şifre kaydediliyor...",

    loggingIn: "Giriş yapılıyor...",
    creatingAccount: "Hesap oluşturuluyor...",
    enterAllFields: "Ad, e-posta ve şifre gir.",
    enterEmailError: "E-posta gir.",
    enterEmailInstruction: "E-posta gir ve sıfırla.",
    sendingRecovery: "E-posta gönderiliyor...",
    recoverySent: "E-posta gönderildi.",
    accountCreated: "Hesap oluşturuldu.",
    signupFailed: "Kayıt başarısız.",
    passwordUpdated: "Şifre güncellendi.",

    readerTitle: "Her metni telaffuz dersine dönüştür",
    yourText: "Metnin",
    pasteHint: "Bir metin yapıştır.",
    createCards: "Kart oluştur",
    saveText: "Kaydet",
    savedTexts: "Kayıtlı metinler",
    practiceCards: "Kartlar",
    practiceHint: "Dinle, kaydet, çevir ve incele.",

    fullText: "Tam metin",
    readComplete: "Tüm metni oku.",
    play: "🔊 Dinle",
    pause: "⏸ Duraklat",
    slowOff: "🐢 Yavaş: kapalı",
    slowOn: "🐢 Yavaş: açık",
    translate: "🌐 Çevir",
    showPinyin: "🔤 Pinyin",
    checkGrammar: "🧠 Dilbilgisi",

    record: "🎤 Kaydet",
    next: "İleri →",
    previous: "← Geri",
    skip: "Atla",
    listening: "Dinleniyor...",
    tryAgain: "Tekrar dene",
    greatJob: "Harika!",

    heroText: "Paste your text, split it into cards, listen, repeat, translate, and check grammar on demand.",
    welcomeMagic: "Welcome to Magic Read",
    listenRepeat: "Listen & Repeat",
    perfectPronunciation: "Perfect your pronunciation",
    smartCards: "Smart Cards",
    studyInteractive: "Study with interactive cards",
    translateLearn: "Translate & Learn",
    understandEverySentence: "Understand every sentence",
    or: "or",

    howItWorks: "How it works",
    howTitle: "From any text to active language practice",

    savedTextsTitle: "Saved texts",
    inputPlaceholder: "Paste your text here...",
  }
};