export const UI_TEXT = {
  en: {
    getStarted: "Get Started",
    logout: "Log out",

    authTitle: "Turn any text into active practice",
    authSubtitle: "Paste a text, listen sentence by sentence, speak, translate, and save useful words.",
    welcomeBack: "Welcome back 👋",
    loginHint: "Log in or create an account to continue.",
    name: "Name",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    login: "Log in",
    createAccount: "Create account",
    enterEmail: "Enter your email",
    restorePassword: "Restore password",
    createNewPassword: "Please create a new password.",
    passwordTooShort: "Password should be at least 6 characters.",
    savingPassword: "Saving new password...",
    loggingIn: "Logging in...",
    creatingAccount: "Creating account...",
    enterAllFields: "Please enter name, email, and password.",
    enterEmailError: "Please enter your email.",
    enterEmailInstruction: "Enter your email and click Restore password.",
    sendingRecovery: "Sending password recovery email...",
    recoverySent: "Password recovery email sent. Please check your inbox.",
    accountCreated: "Account created. Please check your email, then log in.",
    signupFailed: "Signup failed. Please try again.",
    passwordUpdated: "Password updated.",

    welcomeMagic: "Welcome to Magic Read",
    listenRepeat: "Listen & repeat",
    perfectPronunciation: "Practice pronunciation with real texts",
    smartCards: "Save words",
    studyInteractive: "Build flashcards from what you read",
    translateLearn: "Understand faster",
    understandEverySentence: "Translate and explore words in context",
    or: "or",

    library: "Library",
    myTexts: "My texts",
    pasteToStart: "Paste a text to start",
    orLibrary: "or choose one from the library",
    inputPlaceholder: "Paste a text to start",
    start: "Start",
    saveText: "Save text",
    savedTexts: "My texts",
    savedTextsTitle: "My texts",

    ready: "Ready ✓",
    edit: "Edit",
    replace: "Replace",

    fullText: "Full text",
    readComplete: "Read the complete text.",
    play: "Play",
    listen: "Listen",
    listening: "Listening…",
    pause: "Pause",
    slowOff: "Slow: OFF",
    slowOn: "Slow: ON",
    translate: "Translate",
    showTranslation: "Show translation",
    meaning: "Meaning",
    showPinyin: "Pinyin",
    done: "Done",

    practiceCards: "Practice",
    practiceHint: "Listen, speak, and save useful words.",
    record: "Your turn",
    yourTurn: "Your turn",
    stop: "Stop",
    next: "Next",
    previous: "Previous",
    skip: "Skip",

    grammar: "Grammar",
    save: "Save",
    saved: "Saved ✓",

    noWords: "No words yet",
    clickToSave: "Click any word in a text to save it.",
    calligraphy: "Calligraphy"
  },

  ru: {
    getStarted: "Начать",
    logout: "Выйти",

    authTitle: "Превратите любой текст в активную практику",
    authSubtitle: "Вставьте текст, слушайте по предложениям, говорите, переводите и сохраняйте полезные слова.",
    welcomeBack: "С возвращением 👋",
    loginHint: "Войдите или создайте аккаунт, чтобы продолжить.",
    name: "Имя",
    email: "Email",
    password: "Пароль",
    forgotPassword: "Забыли пароль?",
    login: "Войти",
    createAccount: "Создать аккаунт",
    enterEmail: "Введите email",
    restorePassword: "Восстановить пароль",
    createNewPassword: "Создайте новый пароль.",
    passwordTooShort: "Пароль должен содержать минимум 6 символов.",
    savingPassword: "Сохраняем новый пароль...",
    loggingIn: "Выполняется вход...",
    creatingAccount: "Создаём аккаунт...",
    enterAllFields: "Введите имя, email и пароль.",
    enterEmailError: "Введите email.",
    enterEmailInstruction: "Введите email и нажмите «Восстановить пароль».",
    sendingRecovery: "Отправляем письмо для восстановления...",
    recoverySent: "Письмо отправлено. Проверьте почту.",
    accountCreated: "Аккаунт создан. Проверьте почту и войдите.",
    signupFailed: "Ошибка регистрации. Попробуйте снова.",
    passwordUpdated: "Пароль обновлён.",

    welcomeMagic: "Добро пожаловать в Magic Read",
    listenRepeat: "Слушайте и повторяйте",
    perfectPronunciation: "Практикуйте произношение на реальных текстах",
    smartCards: "Сохраняйте слова",
    studyInteractive: "Создавайте карточки из текста",
    translateLearn: "Понимайте быстрее",
    understandEverySentence: "Переводите и изучайте слова в контексте",
    or: "или",

    library: "Библиотека",
    myTexts: "Мои тексты",
    pasteToStart: "Вставьте текст, чтобы начать",
    orLibrary: "или выберите текст из библиотеки",
    inputPlaceholder: "Вставьте текст, чтобы начать",
    start: "Начать",
    saveText: "Сохранить текст",
    savedTexts: "Мои тексты",
    savedTextsTitle: "Мои тексты",

    ready: "Готово ✓",
    edit: "Редактировать",
    replace: "Заменить",

    fullText: "Полный текст",
    readComplete: "Читайте текст целиком.",
    play: "Слушать",
    listen: "Слушать",
    listening: "Слушаем…",
    pause: "Пауза",
    slowOff: "Медленно: выкл.",
    slowOn: "Медленно: вкл.",
    translate: "Перевести",
    showTranslation: "Показать перевод",
    meaning: "Значение",
    showPinyin: "Пиньинь",
    done: "Готово",

    practiceCards: "Практика",
    practiceHint: "Слушайте, говорите и сохраняйте полезные слова.",
    record: "Теперь вы",
    yourTurn: "Теперь вы",
    stop: "Стоп",
    next: "Далее",
    previous: "Назад",
    skip: "Пропустить",

    grammar: "Грамматика",
    save: "Сохранить",
    saved: "Сохранено ✓",

    noWords: "Пока нет слов",
    clickToSave: "Нажмите на любое слово в тексте, чтобы сохранить его.",
    calligraphy: "Каллиграфия"
  },

  zh: {
    getStarted: "开始",
    logout: "退出",

    authTitle: "把任何文本变成主动练习",
    authSubtitle: "粘贴文本，逐句听、说、翻译，并保存有用的词语。",
    welcomeBack: "欢迎回来 👋",
    loginHint: "登录或创建账户继续。",
    name: "姓名",
    email: "邮箱",
    password: "密码",
    forgotPassword: "忘记密码？",
    login: "登录",
    createAccount: "创建账户",
    enterEmail: "请输入邮箱",
    restorePassword: "重置密码",
    createNewPassword: "请创建新密码。",
    passwordTooShort: "密码至少需要 6 个字符。",
    savingPassword: "正在保存新密码...",
    loggingIn: "正在登录...",
    creatingAccount: "正在创建账户...",
    enterAllFields: "请输入姓名、邮箱和密码。",
    enterEmailError: "请输入邮箱。",
    enterEmailInstruction: "请输入邮箱并点击“重置密码”。",
    sendingRecovery: "正在发送邮件...",
    recoverySent: "邮件已发送，请检查邮箱。",
    accountCreated: "账户已创建，请检查邮箱后登录。",
    signupFailed: "注册失败，请重试。",
    passwordUpdated: "密码已更新。",

    welcomeMagic: "欢迎使用 Magic Read",
    listenRepeat: "听并跟读",
    perfectPronunciation: "用真实文本练习发音",
    smartCards: "保存词语",
    studyInteractive: "从阅读中建立词卡",
    translateLearn: "更快理解",
    understandEverySentence: "翻译并在语境中学习词语",
    or: "或",

    library: "文本库",
    myTexts: "我的文本",
    pasteToStart: "粘贴文本开始",
    orLibrary: "或从文本库中选择",
    inputPlaceholder: "粘贴文本开始",
    start: "开始",
    saveText: "保存文本",
    savedTexts: "我的文本",
    savedTextsTitle: "我的文本",

    ready: "准备好了 ✓",
    edit: "编辑",
    replace: "替换",

    fullText: "全文",
    readComplete: "阅读完整文本。",
    play: "播放",
    listen: "听",
    listening: "正在听…",
    pause: "暂停",
    slowOff: "慢速：关",
    slowOn: "慢速：开",
    translate: "翻译",
    showTranslation: "显示翻译",
    meaning: "意思",
    showPinyin: "拼音",
    done: "完成",

    practiceCards: "练习",
    practiceHint: "听、说，并保存有用的词语。",
    record: "轮到你",
    yourTurn: "轮到你",
    stop: "停止",
    next: "下一个",
    previous: "上一个",
    skip: "跳过",

    grammar: "语法",
    save: "保存",
    saved: "已保存 ✓",

    noWords: "还没有词语",
    clickToSave: "点击文本中的任意词语即可保存。",
    calligraphy: "书写"
  },

  tr: {
    getStarted: "Başla",
    logout: "Çıkış yap",

    authTitle: "Her metni aktif pratiğe dönüştür",
    authSubtitle: "Metni yapıştır, cümle cümle dinle, konuş, çevir ve yararlı kelimeleri kaydet.",
    welcomeBack: "Tekrar hoş geldin 👋",
    loginHint: "Devam etmek için giriş yap veya hesap oluştur.",
    name: "Ad",
    email: "E-posta",
    password: "Şifre",
    forgotPassword: "Şifremi unuttum",
    login: "Giriş yap",
    createAccount: "Hesap oluştur",
    enterEmail: "E-posta gir",
    restorePassword: "Şifreyi sıfırla",
    createNewPassword: "Lütfen yeni bir şifre oluştur.",
    passwordTooShort: "Şifre en az 6 karakter olmalı.",
    savingPassword: "Yeni şifre kaydediliyor...",
    loggingIn: "Giriş yapılıyor...",
    creatingAccount: "Hesap oluşturuluyor...",
    enterAllFields: "Ad, e-posta ve şifre gir.",
    enterEmailError: "E-posta gir.",
    enterEmailInstruction: "E-posta gir ve şifreyi sıfırla.",
    sendingRecovery: "E-posta gönderiliyor...",
    recoverySent: "E-posta gönderildi. Lütfen gelen kutunu kontrol et.",
    accountCreated: "Hesap oluşturuldu. Lütfen e-postanı kontrol et ve giriş yap.",
    signupFailed: "Kayıt başarısız. Lütfen tekrar dene.",
    passwordUpdated: "Şifre güncellendi.",

    welcomeMagic: "Magic Read’e hoş geldin",
    listenRepeat: "Dinle ve tekrar et",
    perfectPronunciation: "Gerçek metinlerle telaffuz çalış",
    smartCards: "Kelimeleri kaydet",
    studyInteractive: "Okuduklarından kartlar oluştur",
    translateLearn: "Daha hızlı anla",
    understandEverySentence: "Kelimeleri bağlam içinde çevir ve öğren",
    or: "veya",

    library: "Kütüphane",
    myTexts: "Metinlerim",
    pasteToStart: "Başlamak için metin yapıştır",
    orLibrary: "veya kütüphaneden bir metin seç",
    inputPlaceholder: "Başlamak için metin yapıştır",
    start: "Başla",
    saveText: "Metni kaydet",
    savedTexts: "Metinlerim",
    savedTextsTitle: "Metinlerim",

    ready: "Hazır ✓",
    edit: "Düzenle",
    replace: "Değiştir",

    fullText: "Tam metin",
    readComplete: "Tam metni oku.",
    play: "Dinle",
    listen: "Dinle",
    listening: "Dinleniyor…",
    pause: "Duraklat",
    slowOff: "Yavaş: kapalı",
    slowOn: "Yavaş: açık",
    translate: "Çevir",
    showTranslation: "Çeviriyi göster",
    meaning: "Anlam",
    showPinyin: "Pinyin",
    done: "Bitti",

    practiceCards: "Pratik",
    practiceHint: "Dinle, konuş ve yararlı kelimeleri kaydet.",
    record: "Sıra sende",
    yourTurn: "Sıra sende",
    stop: "Dur",
    next: "İleri",
    previous: "Geri",
    skip: "Atla",

    grammar: "Dilbilgisi",
    save: "Kaydet",
    saved: "Kaydedildi ✓",

    noWords: "Henüz kelime yok",
    clickToSave: "Kaydetmek için metindeki herhangi bir kelimeye tıkla.",
    calligraphy: "Yazı"
  }
};