export const UI_TEXT = {
  en: {
    getStarted: "Get Started",
    logout: "Log out",

    authTitle: "Turn any text into active practice",
    authSubtitle: "Paste a text, listen sentence by sentence, speak, translate, and save useful words.",
    welcomeBack: "Welcome back 👋",
    loginHint: "Log in or create an account to continue.",
    loginTitle: "Welcome back",
    signupTitle: "Create your free account",
    signupTrialHint: "Start your 7-day Pro trial. No payment method required.",
    name: "Name",
    email: "Email",
    password: "Password",
    forgotPassword: "Forgot password?",
    login: "Log in",
    createAccount: "Create account",
    enterEmail: "Enter your email",
    restorePassword: "Restore password",
    createNewPassword: "Please create a new password.",
    passwordTooShort: "Password should be at least 6 characters.",
    savingPassword: "Saving new password...",
    loggingIn: "Logging in...",
    creatingAccount: "Creating account...",
    enterAllFields: "Please enter name, email, and password.",
    enterEmailError: "Please enter your email.",
    enterEmailInstruction: "Enter your email and click Restore password.",
    sendingRecovery: "Sending password recovery email...",
    recoverySent: "Password recovery email sent. Please check your inbox.",
    accountCreated: "Account created. Please check your email, then log in.",
    signupFailed: "Signup failed. Please try again.",
    passwordUpdated: "Password updated.",

    welcomeMagic: "Welcome to Magic Read",
    listenRepeat: "Listen & repeat",
    perfectPronunciation: "Practice pronunciation with real texts",
    smartCards: "Save words",
    studyInteractive: "Build flashcards from what you read",
    translateLearn: "Understand faster",
    understandEverySentence: "Translate and explore words in context",
    or: "or",

    library: "Library",
    myTexts: "My texts",
    pasteToStart: "Practice pronunciation with your own texts",
    orLibrary: "Paste homework, articles, or exam texts and start speaking immediately.",
    inputPlaceholder: "Paste a text to start",
    start: "Start",
    readModeTitle: "Read and understand any text",
    readModeHint: "Paste an article, story, or lesson to get audio, translation, and reading exercises.",
    startReading: "Start reading",
    speakModeTitle: "Practice pronunciation with your own texts",
    speakModeHint: "Paste homework, dialogue, or exam text and get sentence-by-sentence speaking feedback.",
    startSpeaking: "Start speaking",
    trialHeadline: "Try Pro free for 7 days",
    trialHint: "Create a free account to activate your trial. No payment method required, and you will not be charged automatically.",
    trialCreateAccount: "Create free account",
    trialExploreFree: "Explore with free limits",
    chooseLanguages: "Choose languages",
    changeLanguagesLater: "You can change these later in settings.",
    iSpeak: "I speak",
    imLearning: "I'm learning",
    continue: "Continue",
    trialUnlimitedPronunciation: "Unlimited pronunciation checks",
    trialSmartCaptions: "Videos with smart captions",
    trialAllDecks: "All flashcard decks & calligraphy export",
    lifetimeOffer: "Founding lifetime — $89 once",
    tbankPaymentLabel: "Russian card or SBP",
    tbankMonthly: "1 month — 600 ₽",
    tbankAnnual: "1 year — 5,000 ₽",
    tbankPaymentPending: "Payment received. Pro access will appear shortly.",
    tbankPaymentFailed: "Payment was not completed.",
    redirecting: "Redirecting…",
    saveText: "Save text",
    iSpeak: "I speak",
    iLearn: "I learn",
    savedTexts: "My texts",
    savedTextsTitle: "My texts",

    ready: "Ready ✓",
    edit: "Edit",
    replace: "Replace",

    fullText: "Full text",
    readComplete: "Read the complete text.",
    play: "Play",
    listen: "Listen",
    listening: "Listening…",
    pause: "Pause",
    slowOff: "Slow: OFF",
    slowOn: "Slow: ON",
    slow: "Slow",
    more: "More",
    translate: "Translate",
    showTranslation: "Show translation",
    meaning: "Meaning",
    showPinyin: "Pinyin",
    done: "Done",

    practiceCards: "Practice",
    practiceHint: "Listen, speak, and save useful words.",
    exerciseEyebrow: "After reading",
    exerciseTitle: "Fill in the gaps",
    exerciseHint: "Pick the missing word for each gap, then check your answers.",
    checkAnswers: "Check answers",
    showAnswers: "Show answers",
    exerciseSavedNote: "Gaps use words you've saved to flashcards.",
    exerciseKeyNote: "Save words from this text to flashcards to make this quiz about your vocabulary.",
    exerciseEmpty: "Save a few words from this text to flashcards, then reopen Reading — we'll quiz you on them.",
    record: "Your turn",
    yourTurn: "Your turn",
    stop: "Stop",
    next: "Next",
    previous: "Previous",

    // Tutor-style pronunciation drill
    drillPracticeThis: "Let's practice this part",
    drillHear: "Hear it",
    drillRepeat: "Repeat it",
    drillSkip: "Skip",
    drillGotIt: "Got it!",
    drillAlmost: "Almost — listen again and repeat.",
    drillTriesLeft: "tries left",
    drillKeepGoing: "Close — keep practicing this one. Let's move on for now.",
    drillFocus: "Focus on",
    drillMissed: "missed",
    drillSkipped: "Skipped — moving on.",
    drillMastered: "Nice — you nailed every part! 🎉",
    drillNoSpeech: "I didn't hear anything. Tap Repeat and speak.",
    drillMicDenied: "Microphone is blocked. Allow mic access and try again.",
    drillBusy: "Service is busy. Tap Repeat to try again.",
    drillTryAgain: "Tap Repeat to try again.",
    drillQuota: "You've used today's free pronunciation checks. Upgrade for unlimited.",
    skip: "Skip",

    grammar: "Grammar",
    save: "Save",
    flashcards: "Flashcards",

    noWords: "No words yet",
    clickToSave: "Click any word in a text to save it.",
    calligraphy: "Calligraphy",

    backToReading: "← Back to reading",
    newDeck: "New deck",
    deleteDeck: "Delete deck",
    clear: "Clear",
    exportPDF: "Export PDF",
    wordLabel: "Word",
    context: "Context",
    delete: "Delete",
    calligraphyHint: "Chinese and Russian only",
    writingPlaceholder: "Paste characters or words",
    createSheet: "Create sheet",
    card: "Card",
    of: "of",
    deck: "Deck",
    createAccountHint: "Create an account to save your texts, vocabulary, and practice.",
    loginToContinue: "Log in to start practicing",
    cardsTitle: "Cards",
    cardsSubtitle: "Save new words from text or upload your own list",
    fcBrowse: "Browse",
    fcLearnTab: "Learn",
    fcCheckTab: "Check",
    speakTermMode: "Speak: Term",
    speakTranslationMode: "Speak: Translation",
    exitSpeaking: "Exit speaking",
    importWords: "Import words",
    deleteCard: "Delete card",
    sayIt: "Say it",
    practiceAgain: "Practice again",
    answeredCorrectly: "answered correctly",
    typedCorrectly: "typed correctly",
    typeTheWord: "Type the word",
    correctAnswerIs: "Correct answer:",
    correctExcl: "Correct!",
    seeResult: "See result",
    check: "Check",
    learnLocked: "Learn needs at least 5 cards in the deck.",
    noCardsInDeck: "No cards in deck.",
    comprehensionExercise: "Comprehension exercise",
    readingTitle: "Reading",
    sentenceOne: "sentence",
    sentenceMany: "sentences",
    speedHint: "Tap turtle twice for 0.75×",
    rdSetupTitle: "What would you like to read today?",
    pasteTextTab: "Paste text",
    libraryTab: "Library",
    savedTab: "Saved",
    rdSetupPlaceholder: "Paste a text here — an article, a chat, song lyrics or homework. We'll add pinyin, audio and word lookups automatically.",
    charactersLabel: "characters",
    exerciseWord: "Exercise",
    putWordsInOrder: "Put the words in order",
    chooseMissingWord: "Choose the missing word",
    rebuildScrambled: "Rebuild the scrambled sentence.",
    whichWordCompletes: "Which word completes the sentence?",
    correctOrder: "Correct order.",
    notQuiteTapBack: "Not quite — tap a tile to send it back.",
    notQuiteTryAgain: "Not quite — try again.",
    completedLabel: "completed",
    notEnoughText: "Not enough text for this exercise.",
    listenFirst: "Listen first",
    tapToSpeak: "Tap to speak, tap again when you're done",
    speakNowTapDone: "Speak now — tap again when you're done",
    scoringLabel: "Scoring…",
    playingAudio: "Playing audio…",
    sentenceWord: "Sentence",
    textComplete: "Text complete",
    nicelyDone: "Nicely done!",
    youSpokeAll: "You spoke all",
    sentencesOutLoud: "sentences out loud.",
    overallLabel: "Overall",
    tapToRetrySentence: "Tap a sentence to practise it again",
    pasteAnotherText: "Paste another text",
    chooseFromLibrary: "Choose from Library",
    pasteYouTubeLink: "Paste YouTube link…",
    loadBtn: "Load",
    pasteLinkAbove: "Paste a YouTube link above",
    loadingCaptions: "Loading captions…",
    noCaptionsTitle: "No captions found",
    noCaptionsSub: "The video opened, but we could not find usable captions for the learning language.",
    tryAnotherVideo: "Try another video",
    captionsUnavailable: "Captions temporarily unavailable",
    tryAgain: "Try again",
    speakThisLine: "Speak this line",
    translatePill: "Translate",
    pinyinPill: "Pinyin",
    romajiPill: "Romaji",
    quotaChecksTitle: "You're out of today's free checks",
    quotaChecksSub: "You've used all {n} pronunciation checks for today. Go Pro for unlimited practice — no daily cap.",
    quotaResetTomorrow: "Your free checks reset tomorrow.",
    quotaTextsTitle: "That's your free texts for today",
    quotaTextsSub: "You've added {n} texts today. Go Pro to add as many as you like.",
    quotaSavedSub: "You've saved {n} texts (free limit). Go Pro to save as many as you like.",
    quotaLimitTitle: "You've reached the free limit",
    quotaDeckSub: "Free decks are capped at {n}. Go Pro for unlimited decks and cards.",
    quotaCardSub: "Your deck has {n} cards (free limit). Go Pro for unlimited cards.",
    quotaVideoTitle: "Videos are a Pro feature",
    quotaVideoSub: "You've used your {n} trial videos. Go Pro to keep learning from any video.",
    quotaTtsTitle: "You've used today's free audio",
    quotaTtsSub: "Go Pro for unlimited listening — no daily cap.",
    quotaTtsReset: "Your free audio resets tomorrow.",
    quotaTransTitle: "You've used today's free translations",
    quotaTransSub: "Go Pro for unlimited translations — no daily cap.",
    quotaTransReset: "Your free translations reset tomorrow.",
    upgradeDefaultTitle: "Upgrade to Pro",
    upgradeDefaultSub: "Go Pro for unlimited access.",
    cmpTextsDay: "Texts / day",
    cmpChecksDay: "Pronunciation checks / day",
    cmpSavedTexts: "Saved texts",
    cmpDecksCards: "Decks · cards",
    cmpVideos: "Videos with captions",
    freeLabel: "Free",
    proLabel: "Pro",
    maybeLater: "Maybe later",
    annualPlanBtn: "Annual — $49/yr",
    monthlyPlanBtn: "Monthly — $6.99/mo",
    savePct: "Save 41%",
    freePlanLabel: "Free plan",

    saved: "Saved",
    savedTextsError: "Could not load saved texts.",
    hidePinyin: "Hide pinyin",
    voice: "Voice",
    voicePickerHeading: "Choose a voice for this language",
    wordSaveHint: "Tip: click any word to hear it, translate it, and save it to flashcards.",
    hideFullText: "Hide full text",
    showFullText: "Show full text",
    grammarFailed: "Grammar check failed.",
    pinyinError: "Could not load pinyin."
  },

  ru: {
    getStarted: "Начать",
    logout: "Выйти",

    authTitle: "Превратите любой текст в активную практику",
    authSubtitle: "Вставьте текст, слушайте по предложениям, говорите, переводите и сохраняйте полезные слова.",
    welcomeBack: "С возвращением 👋",
    loginHint: "Войдите или создайте аккаунт, чтобы продолжить.",
    loginTitle: "С возвращением",
    signupTitle: "Создайте бесплатный аккаунт",
    signupTrialHint: "Начните 7-дневный Pro-период. Банковская карта не требуется.",
    name: "Имя",
    email: "Email",
    password: "Пароль",
    forgotPassword: "Забыли пароль?",
    login: "Войти",
    createAccount: "Создать аккаунт",
    enterEmail: "Введите email",
    restorePassword: "Восстановить пароль",
    createNewPassword: "Создайте новый пароль.",
    passwordTooShort: "Пароль должен содержать минимум 6 символов.",
    savingPassword: "Сохраняем новый пароль...",
    loggingIn: "Выполняется вход...",
    creatingAccount: "Создаём аккаунт...",
    enterAllFields: "Введите имя, email и пароль.",
    enterEmailError: "Введите email.",
    enterEmailInstruction: "Введите email и нажмите «Восстановить пароль».",
    sendingRecovery: "Отправляем письмо для восстановления...",
    recoverySent: "Письмо отправлено. Проверьте почту.",
    accountCreated: "Аккаунт создан. Проверьте почту и войдите.",
    signupFailed: "Ошибка регистрации. Попробуйте снова.",
    passwordUpdated: "Пароль обновлён.",

    welcomeMagic: "Добро пожаловать в Magic Read",
    listenRepeat: "Слушайте и повторяйте",
    perfectPronunciation: "Практикуйте произношение на реальных текстах",
    smartCards: "Сохраняйте слова",
    studyInteractive: "Создавайте карточки из текста",
    translateLearn: "Понимайте быстрее",
    understandEverySentence: "Переводите и изучайте слова в контексте",
    or: "или",

    library: "Библиотека",
    myTexts: "Мои тексты",
    pasteToStart: "Вставьте текст, чтобы начать",
    orLibrary: "или выберите текст из библиотеки",
    inputPlaceholder: "Вставьте текст, чтобы начать",
    start: "Начать",
    readModeTitle: "Читайте и понимайте любой текст",
    readModeHint: "Вставьте статью, рассказ или урок, чтобы получить озвучку, перевод и упражнения.",
    startReading: "Начать чтение",
    speakModeTitle: "Тренируйте произношение на своих текстах",
    speakModeHint: "Вставьте домашнее задание, диалог или экзаменационный текст и получите обратную связь по каждому предложению.",
    startSpeaking: "Начать говорить",
    trialHeadline: "Попробуйте Pro бесплатно 7 дней",
    trialHint: "Создайте бесплатный аккаунт, чтобы активировать пробный период. Карта не нужна, автоматического списания не будет.",
    trialCreateAccount: "Создать бесплатный аккаунт",
    trialExploreFree: "Попробовать с бесплатными лимитами",
    chooseLanguages: "Выберите языки",
    changeLanguagesLater: "Их можно изменить позже в настройках.",
    iSpeak: "Я говорю на",
    imLearning: "Я изучаю",
    continue: "Продолжить",
    trialUnlimitedPronunciation: "Неограниченная проверка произношения",
    trialSmartCaptions: "Видео с умными субтитрами",
    trialAllDecks: "Все колоды и экспорт прописей",
    lifetimeOffer: "Пожизненный доступ для первых пользователей — $89",
    tbankPaymentLabel: "Карта РФ или СБП",
    tbankMonthly: "1 месяц — 600 ₽",
    tbankAnnual: "1 год — 5 000 ₽",
    tbankPaymentPending: "Платёж принят. Доступ Pro появится в ближайшее время.",
    tbankPaymentFailed: "Платёж не был завершён.",
    redirecting: "Переходим к оплате…",
    saveText: "Сохранить текст",
    iSpeak: "Я говорю на",
    iLearn: "Я учу",
    savedTexts: "Мои тексты",
    savedTextsTitle: "Мои тексты",

    ready: "Готово ✓",
    edit: "Редактировать",
    replace: "Заменить",

    fullText: "Полный текст",
    readComplete: "Читайте текст целиком.",
    play: "Слушать",
    listen: "Слушать",
    listening: "Слушаем…",
    pause: "Пауза",
    slowOff: "Медленно: выкл.",
    slowOn: "Медленно: вкл.",
    translate: "Перевести",
    showTranslation: "Показать перевод",
    meaning: "Значение",
    showPinyin: "Пиньинь",
    done: "Готово",

    practiceCards: "Практика",
    practiceHint: "Слушайте, говорите и сохраняйте полезные слова.",
    record: "Теперь вы",
    yourTurn: "Теперь вы",
    stop: "Стоп",
    next: "Далее",
    previous: "Назад",
    skip: "Пропустить",

    grammar: "Грамматика",
    save: "Сохранить",
    flashcards: "Карточки",

    noWords: "Пока нет слов",
    clickToSave: "Нажмите на любое слово в тексте, чтобы сохранить его.",
    calligraphy: "Каллиграфия",

    backToReading: "← Назад к чтению",
    newDeck: "Новая колода",
    deleteDeck: "Удалить колоду",
    clear: "Очистить",
    exportPDF: "Экспорт PDF",
    wordLabel: "Слово",
    context: "Контекст",
    delete: "Удалить",
    calligraphyHint: "Только китайский и русский",
    writingPlaceholder: "Вставьте слова или фразы",
    createSheet: "Создать лист",
    card: "Карточка",
    of: "из",
    deck: "Колода",
    createAccountHint: "Создайте аккаунт, чтобы сохранять тексты, словарь и прогресс.",
    loginToContinue: "Войдите, чтобы начать практику",
    cardsTitle: "Карточки",
    cardsSubtitle: "Сохраняйте новые слова из текстов или загрузите свой список",
    fcBrowse: "Просмотр",
    fcLearnTab: "Учить",
    fcCheckTab: "Проверка",
    speakTermMode: "Произнести: слово",
    speakTranslationMode: "Произнести: перевод",
    exitSpeaking: "Выйти из практики",
    importWords: "Импорт слов",
    deleteCard: "Удалить карточку",
    sayIt: "Произнесите",
    practiceAgain: "Повторить ещё раз",
    answeredCorrectly: "правильных ответов",
    typedCorrectly: "верно введено",
    typeTheWord: "Введите слово",
    correctAnswerIs: "Правильный ответ:",
    correctExcl: "Верно!",
    seeResult: "К результату",
    check: "Проверить",
    learnLocked: "Для режима «Учить» нужно минимум 5 карточек в колоде.",
    noCardsInDeck: "В колоде нет карточек.",
    comprehensionExercise: "Упражнение на понимание",
    readingTitle: "Чтение",
    sentenceOne: "предложение",
    sentenceMany: "предложений",
    speedHint: "Нажмите на черепаху дважды для 0.75×",
    rdSetupTitle: "Что почитаем сегодня?",
    pasteTextTab: "Вставить текст",
    libraryTab: "Библиотека",
    savedTab: "Сохранённые",
    rdSetupPlaceholder: "Вставьте текст — статью, переписку, слова песни или домашнее задание. Мы автоматически добавим транскрипцию, озвучку и перевод слов.",
    charactersLabel: "символов",
    exerciseWord: "Упражнение",
    putWordsInOrder: "Расставьте слова по порядку",
    chooseMissingWord: "Выберите пропущенное слово",
    rebuildScrambled: "Соберите предложение из слов.",
    whichWordCompletes: "Какое слово завершает предложение?",
    correctOrder: "Правильный порядок!",
    notQuiteTapBack: "Не совсем — нажмите на плитку, чтобы вернуть её.",
    notQuiteTryAgain: "Не совсем — попробуйте ещё раз.",
    completedLabel: "выполнено",
    notEnoughText: "Недостаточно текста для этого упражнения.",
    listenFirst: "Сначала послушать",
    tapToSpeak: "Нажмите и говорите, нажмите ещё раз, когда закончите",
    speakNowTapDone: "Говорите — нажмите ещё раз, когда закончите",
    scoringLabel: "Оцениваем…",
    playingAudio: "Воспроизведение…",
    sentenceWord: "Предложение",
    textComplete: "Текст пройден",
    nicelyDone: "Отлично!",
    youSpokeAll: "Вы произнесли все",
    sentencesOutLoud: "предложений вслух.",
    overallLabel: "Итог",
    tapToRetrySentence: "Нажмите на предложение, чтобы повторить его",
    pasteAnotherText: "Вставить другой текст",
    chooseFromLibrary: "Выбрать из библиотеки",
    pasteYouTubeLink: "Вставьте ссылку YouTube…",
    loadBtn: "Открыть",
    pasteLinkAbove: "Вставьте ссылку YouTube выше",
    loadingCaptions: "Загружаем субтитры…",
    noCaptionsTitle: "Субтитры не найдены",
    noCaptionsSub: "Видео открылось, но субтитров на изучаемом языке не нашлось.",
    tryAnotherVideo: "Попробовать другое видео",
    captionsUnavailable: "Субтитры временно недоступны",
    tryAgain: "Попробовать снова",
    speakThisLine: "Произнести эту фразу",
    translatePill: "Перевод",
    pinyinPill: "Пиньинь",
    romajiPill: "Ромадзи",
    quotaChecksTitle: "Бесплатные проверки на сегодня закончились",
    quotaChecksSub: "Вы использовали все {n} проверок произношения на сегодня. С Pro — безлимит, без дневных ограничений.",
    quotaResetTomorrow: "Бесплатные проверки обновятся завтра.",
    quotaTextsTitle: "Бесплатные тексты на сегодня закончились",
    quotaTextsSub: "Вы добавили {n} текста сегодня. С Pro — сколько угодно.",
    quotaSavedSub: "Вы сохранили {n} текстов (лимит бесплатного плана). С Pro — без ограничений.",
    quotaLimitTitle: "Вы достигли лимита бесплатного плана",
    quotaDeckSub: "В бесплатном плане не больше {n} колод. С Pro — колоды и карточки без ограничений.",
    quotaCardSub: "В колоде {n} карточек (лимит бесплатного плана). С Pro — без ограничений.",
    quotaVideoTitle: "Видео — функция Pro",
    quotaVideoSub: "Вы использовали {n} пробных видео. С Pro — учитесь по любым видео.",
    quotaTtsTitle: "Бесплатная озвучка на сегодня закончилась",
    quotaTtsSub: "С Pro — безлимитная озвучка без дневных ограничений.",
    quotaTtsReset: "Бесплатная озвучка обновится завтра.",
    quotaTransTitle: "Бесплатные переводы на сегодня закончились",
    quotaTransSub: "С Pro — безлимитные переводы без дневных ограничений.",
    quotaTransReset: "Бесплатные переводы обновятся завтра.",
    upgradeDefaultTitle: "Перейти на Pro",
    upgradeDefaultSub: "С Pro — безлимитный доступ ко всему.",
    cmpTextsDay: "Текстов в день",
    cmpChecksDay: "Проверок произношения в день",
    cmpSavedTexts: "Сохранённые тексты",
    cmpDecksCards: "Колоды · карточки",
    cmpVideos: "Видео с субтитрами",
    freeLabel: "Free",
    proLabel: "Pro",
    maybeLater: "Позже",
    annualPlanBtn: "Годовой — $49/год",
    monthlyPlanBtn: "Месячный — $6.99/мес",
    savePct: "Экономия 41%",
    freePlanLabel: "Бесплатный план",

    saved: "Сохранено",
    savedTextsError: "Не удалось загрузить тексты.",
    hidePinyin: "Скрыть пиньинь",
    voice: "Голос",
    voicePickerHeading: "Выберите голос для этого языка",
    wordSaveHint: "Совет: нажмите на любое слово, чтобы услышать, перевести и сохранить его.",
    hideFullText: "Скрыть текст",
    showFullText: "Показать текст",
    grammarFailed: "Ошибка проверки грамматики.",
    pinyinError: "Не удалось загрузить пиньинь."
  },

  zh: {
    getStarted: "开始",
    logout: "退出",

    authTitle: "把任何文本变成主动练习",
    authSubtitle: "粘贴文本，逐句听、说、翻译，并保存有用的词语。",
    welcomeBack: "欢迎回来 👋",
    loginHint: "登录或创建账户继续。",
    loginTitle: "欢迎回来",
    signupTitle: "创建免费账户",
    signupTrialHint: "开始 7 天 Pro 试用，无需付款方式。",
    name: "姓名",
    email: "邮箱",
    password: "密码",
    forgotPassword: "忘记密码？",
    login: "登录",
    createAccount: "创建账户",
    enterEmail: "请输入邮箱",
    restorePassword: "重置密码",
    createNewPassword: "请创建新密码。",
    passwordTooShort: "密码至少需要 6 个字符。",
    savingPassword: "正在保存新密码...",
    loggingIn: "正在登录...",
    creatingAccount: "正在创建账户...",
    enterAllFields: "请输入姓名、邮箱和密码。",
    enterEmailError: "请输入邮箱。",
    enterEmailInstruction: "请输入邮箱并点击“重置密码”。",
    sendingRecovery: "正在发送邮件...",
    recoverySent: "邮件已发送，请检查邮箱。",
    accountCreated: "账户已创建，请检查邮箱后登录。",
    signupFailed: "注册失败，请重试。",
    passwordUpdated: "密码已更新。",

    welcomeMagic: "欢迎使用 Magic Read",
    listenRepeat: "听并跟读",
    perfectPronunciation: "用真实文本练习发音",
    smartCards: "保存词语",
    studyInteractive: "从阅读中建立词卡",
    translateLearn: "更快理解",
    understandEverySentence: "翻译并在语境中学习词语",
    or: "或",

    library: "文本库",
    myTexts: "我的文本",
    pasteToStart: "粘贴文本开始",
    orLibrary: "或从文本库中选择",
    inputPlaceholder: "粘贴文本开始",
    start: "开始",
    readModeTitle: "阅读并理解任何文本",
    readModeHint: "粘贴文章、故事或课程，即可获得朗读、翻译和阅读练习。",
    startReading: "开始阅读",
    speakModeTitle: "用自己的文本练习发音",
    speakModeHint: "粘贴作业、对话或考试文本，获得逐句口语反馈。",
    startSpeaking: "开始口语练习",
    trialHeadline: "免费试用 Pro 7 天",
    trialHint: "创建免费账户即可激活试用。无需付款方式，也不会自动扣费。",
    trialCreateAccount: "创建免费账户",
    trialExploreFree: "使用免费额度体验",
    chooseLanguages: "选择语言",
    changeLanguagesLater: "之后可在设置中更改。",
    iSpeak: "我会说",
    imLearning: "我正在学习",
    continue: "继续",
    trialUnlimitedPronunciation: "无限次发音评估",
    trialSmartCaptions: "智能字幕视频",
    trialAllDecks: "全部词卡组与字帖导出",
    lifetimeOffer: "创始用户终身版 — 一次性 $89",
    tbankPaymentLabel: "俄罗斯银行卡或 SBP",
    tbankMonthly: "1 个月 — 600 ₽",
    tbankAnnual: "1 年 — 5,000 ₽",
    tbankPaymentPending: "付款已收到，Pro 权限即将生效。",
    tbankPaymentFailed: "付款未完成。",
    redirecting: "正在跳转…",
    saveText: "保存文本",
    iSpeak: "我说",
    iLearn: "我学",
    savedTexts: "我的文本",
    savedTextsTitle: "我的文本",

    ready: "准备好了 ✓",
    edit: "编辑",
    replace: "替换",

    fullText: "全文",
    readComplete: "阅读完整文本。",
    play: "播放",
    listen: "听",
    listening: "正在听…",
    pause: "暂停",
    slowOff: "慢速：关",
    slowOn: "慢速：开",
    translate: "翻译",
    showTranslation: "显示翻译",
    meaning: "意思",
    showPinyin: "拼音",
    done: "完成",

    practiceCards: "练习",
    practiceHint: "听、说，并保存有用的词语。",
    record: "轮到你",
    yourTurn: "轮到你",
    stop: "停止",
    next: "下一个",
    previous: "上一个",
    skip: "跳过",

    grammar: "语法",
    save: "保存",
    flashcards: "词卡",

    noWords: "还没有词语",
    clickToSave: "点击文本中的任意词语即可保存。",
    calligraphy: "书写",

    backToReading: "← 返回阅读",
    newDeck: "新建词组",
    deleteDeck: "删除词组",
    clear: "清空",
    exportPDF: "导出 PDF",
    wordLabel: "词语",
    context: "语境",
    delete: "删除",
    calligraphyHint: "仅支持中文和俄文",
    writingPlaceholder: "粘贴汉字或词语",
    createSheet: "创建练习表",
    card: "卡片",
    of: "/",
    deck: "词组",
    createAccountHint: "创建账户以保存文本、词汇和练习记录。",
    loginToContinue: "登录后开始练习",
    cardsTitle: "卡片",
    cardsSubtitle: "从课文中保存生词，或上传自己的单词表",
    fcBrowse: "浏览",
    fcLearnTab: "学习",
    fcCheckTab: "测验",
    speakTermMode: "朗读：词语",
    speakTranslationMode: "朗读：翻译",
    exitSpeaking: "退出朗读",
    importWords: "导入单词",
    deleteCard: "删除卡片",
    sayIt: "说说看",
    practiceAgain: "再练一次",
    answeredCorrectly: "答对",
    typedCorrectly: "输入正确",
    typeTheWord: "输入词语",
    correctAnswerIs: "正确答案：",
    correctExcl: "答对了！",
    seeResult: "查看结果",
    check: "检查",
    learnLocked: "「学习」模式需要牌组中至少有 5 张卡片。",
    noCardsInDeck: "牌组中没有卡片。",
    comprehensionExercise: "理解练习",
    readingTitle: "阅读",
    sentenceOne: "个句子",
    sentenceMany: "个句子",
    speedHint: "点两次乌龟可减速至 0.75×",
    rdSetupTitle: "今天想读点什么？",
    pasteTextTab: "粘贴文本",
    libraryTab: "文库",
    savedTab: "已保存",
    rdSetupPlaceholder: "在这里粘贴文本——文章、聊天记录、歌词或作业。我们会自动添加拼音、语音和单词释义。",
    charactersLabel: "字符",
    exerciseWord: "练习",
    putWordsInOrder: "连词成句",
    chooseMissingWord: "选择缺少的词",
    rebuildScrambled: "把打乱的句子重新组合。",
    whichWordCompletes: "哪个词能补全句子？",
    correctOrder: "顺序正确。",
    notQuiteTapBack: "不太对——点一下词块把它放回去。",
    notQuiteTryAgain: "不太对——再试一次。",
    completedLabel: "已完成",
    notEnoughText: "文本不够，无法生成这个练习。",
    listenFirst: "先听一遍",
    tapToSpeak: "点击开始朗读，说完后再点一次",
    speakNowTapDone: "请开始朗读——说完后再点一次",
    scoringLabel: "评分中…",
    playingAudio: "播放中…",
    sentenceWord: "句子",
    textComplete: "文本完成",
    nicelyDone: "做得好！",
    youSpokeAll: "你朗读了全部",
    sentencesOutLoud: "个句子。",
    overallLabel: "总分",
    tapToRetrySentence: "点击句子可再次练习",
    pasteAnotherText: "粘贴新文本",
    chooseFromLibrary: "从文库选择",
    pasteYouTubeLink: "粘贴 YouTube 链接…",
    loadBtn: "加载",
    pasteLinkAbove: "在上方粘贴 YouTube 链接",
    loadingCaptions: "正在加载字幕…",
    noCaptionsTitle: "未找到字幕",
    noCaptionsSub: "视频已打开，但没有找到所学语言的可用字幕。",
    tryAnotherVideo: "换个视频试试",
    captionsUnavailable: "字幕暂时不可用",
    tryAgain: "重试",
    speakThisLine: "朗读这一句",
    translatePill: "翻译",
    pinyinPill: "拼音",
    romajiPill: "罗马字",
    quotaChecksTitle: "今天的免费发音评测已用完",
    quotaChecksSub: "今天的 {n} 次发音评测已全部用完。升级 Pro 即可无限练习，没有每日上限。",
    quotaResetTomorrow: "免费次数明天重置。",
    quotaTextsTitle: "今天的免费文本已用完",
    quotaTextsSub: "今天已添加 {n} 篇文本。升级 Pro 可无限添加。",
    quotaSavedSub: "已保存 {n} 篇文本（免费上限）。升级 Pro 可无限保存。",
    quotaLimitTitle: "已达到免费上限",
    quotaDeckSub: "免费牌组上限为 {n} 个。升级 Pro 可无限创建牌组和卡片。",
    quotaCardSub: "牌组已有 {n} 张卡片（免费上限）。升级 Pro 可无限添加。",
    quotaVideoTitle: "视频是 Pro 功能",
    quotaVideoSub: "{n} 个试用视频已用完。升级 Pro 可继续用任意视频学习。",
    quotaTtsTitle: "今天的免费语音已用完",
    quotaTtsSub: "升级 Pro 可无限收听，没有每日上限。",
    quotaTtsReset: "免费语音明天重置。",
    quotaTransTitle: "今天的免费翻译已用完",
    quotaTransSub: "升级 Pro 可无限翻译，没有每日上限。",
    quotaTransReset: "免费翻译明天重置。",
    upgradeDefaultTitle: "升级到 Pro",
    upgradeDefaultSub: "升级 Pro 解锁全部功能。",
    cmpTextsDay: "文本 / 天",
    cmpChecksDay: "发音评测 / 天",
    cmpSavedTexts: "保存的文本",
    cmpDecksCards: "牌组 · 卡片",
    cmpVideos: "带字幕的视频",
    freeLabel: "免费",
    proLabel: "Pro",
    maybeLater: "以后再说",
    annualPlanBtn: "年付 — $49/年",
    monthlyPlanBtn: "月付 — $6.99/月",
    savePct: "省 41%",
    freePlanLabel: "免费版",

    saved: "已保存",
    savedTextsError: "无法加载已保存的文本。",
    hidePinyin: "隐藏拼音",
    voice: "语音",
    voicePickerHeading: "为该语言选择语音",
    wordSaveHint: "提示：点击任意词语可以听读、翻译并保存到词卡。",
    hideFullText: "隐藏全文",
    showFullText: "显示全文",
    grammarFailed: "语法检查失败。",
    pinyinError: "无法加载拼音。"
  },

  tr: {
    getStarted: "Başla",
    logout: "Çıkış yap",

    authTitle: "Her metni aktif pratiğe dönüştür",
    authSubtitle: "Metni yapıştır, cümle cümle dinle, konuş, çevir ve yararlı kelimeleri kaydet.",
    welcomeBack: "Tekrar hoş geldin 👋",
    loginHint: "Devam etmek için giriş yap veya hesap oluştur.",
    loginTitle: "Tekrar hoş geldin",
    signupTitle: "Ücretsiz hesabını oluştur",
    signupTrialHint: "7 günlük Pro denemeni başlat. Ödeme yöntemi gerekmez.",
    name: "Ad",
    email: "E-posta",
    password: "Şifre",
    forgotPassword: "Şifremi unuttum",
    login: "Giriş yap",
    createAccount: "Hesap oluştur",
    enterEmail: "E-posta gir",
    restorePassword: "Şifreyi sıfırla",
    createNewPassword: "Lütfen yeni bir şifre oluştur.",
    passwordTooShort: "Şifre en az 6 karakter olmalı.",
    savingPassword: "Yeni şifre kaydediliyor...",
    loggingIn: "Giriş yapılıyor...",
    creatingAccount: "Hesap oluşturuluyor...",
    enterAllFields: "Ad, e-posta ve şifre gir.",
    enterEmailError: "E-posta gir.",
    enterEmailInstruction: "E-posta gir ve şifreyi sıfırla.",
    sendingRecovery: "E-posta gönderiliyor...",
    recoverySent: "E-posta gönderildi. Lütfen gelen kutunu kontrol et.",
    accountCreated: "Hesap oluşturuldu. Lütfen e-postanı kontrol et ve giriş yap.",
    signupFailed: "Kayıt başarısız. Lütfen tekrar dene.",
    passwordUpdated: "Şifre güncellendi.",

    welcomeMagic: "Magic Read’e hoş geldin",
    listenRepeat: "Dinle ve tekrar et",
    perfectPronunciation: "Gerçek metinlerle telaffuz çalış",
    smartCards: "Kelimeleri kaydet",
    studyInteractive: "Okuduklarından kartlar oluştur",
    translateLearn: "Daha hızlı anla",
    understandEverySentence: "Kelimeleri bağlam içinde çevir ve öğren",
    or: "veya",

    library: "Kütüphane",
    myTexts: "Metinlerim",
    pasteToStart: "Başlamak için metin yapıştır",
    orLibrary: "veya kütüphaneden bir metin seç",
    inputPlaceholder: "Başlamak için metin yapıştır",
    start: "Başla",
    readModeTitle: "Her metni oku ve anla",
    readModeHint: "Ses, çeviri ve okuma alıştırmaları için bir makale, hikâye veya ders yapıştır.",
    startReading: "Okumaya başla",
    speakModeTitle: "Kendi metinlerinle telaffuz çalış",
    speakModeHint: "Ödev, diyalog veya sınav metni yapıştır ve cümle cümle konuşma geri bildirimi al.",
    startSpeaking: "Konuşmaya başla",
    trialHeadline: "Pro'yu 7 gün ücretsiz dene",
    trialHint: "Denemeyi etkinleştirmek için ücretsiz hesap oluştur. Ödeme yöntemi gerekmez ve otomatik ücret alınmaz.",
    trialCreateAccount: "Ücretsiz hesap oluştur",
    trialExploreFree: "Ücretsiz sınırlarla keşfet",
    chooseLanguages: "Dilleri seç",
    changeLanguagesLater: "Bunları daha sonra ayarlardan değiştirebilirsin.",
    iSpeak: "Konuştuğum dil",
    imLearning: "Öğrendiğim dil",
    continue: "Devam et",
    trialUnlimitedPronunciation: "Sınırsız telaffuz kontrolü",
    trialSmartCaptions: "Akıllı altyazılı videolar",
    trialAllDecks: "Tüm kart desteleri ve yazı çalışma sayfaları",
    lifetimeOffer: "Kurucu ömür boyu erişim — tek seferlik $89",
    tbankPaymentLabel: "Rus kartı veya SBP",
    tbankMonthly: "1 ay — 600 ₽",
    tbankAnnual: "1 yıl — 5.000 ₽",
    tbankPaymentPending: "Ödeme alındı. Pro erişimi kısa süre içinde açılacak.",
    tbankPaymentFailed: "Ödeme tamamlanmadı.",
    redirecting: "Yönlendiriliyor…",
    saveText: "Metni kaydet",
    iSpeak: "Konuştuğum dil",
    iLearn: "Öğrendiğim dil",
    savedTexts: "Metinlerim",
    savedTextsTitle: "Metinlerim",

    ready: "Hazır ✓",
    edit: "Düzenle",
    replace: "Değiştir",

    fullText: "Tam metin",
    readComplete: "Tam metni oku.",
    play: "Dinle",
    listen: "Dinle",
    listening: "Dinleniyor…",
    pause: "Duraklat",
    slowOff: "Yavaş: kapalı",
    slowOn: "Yavaş: açık",
    translate: "Çevir",
    showTranslation: "Çeviriyi göster",
    meaning: "Anlam",
    showPinyin: "Pinyin",
    done: "Bitti",

    practiceCards: "Pratik",
    practiceHint: "Dinle, konuş ve yararlı kelimeleri kaydet.",
    record: "Sıra sende",
    yourTurn: "Sıra sende",
    stop: "Dur",
    next: "İleri",
    previous: "Geri",
    skip: "Atla",

    grammar: "Dilbilgisi",
    save: "Kaydet",
    flashcards: "Kartlar",

    noWords: "Henüz kelime yok",
    clickToSave: "Kaydetmek için metindeki herhangi bir kelimeye tıkla.",
    calligraphy: "Yazı",

    backToReading: "← Okumaya geri dön",
    newDeck: "Yeni deste",
    deleteDeck: "Desteyi sil",
    clear: "Temizle",
    exportPDF: "PDF'e aktar",
    wordLabel: "Kelime",
    context: "Bağlam",
    delete: "Sil",
    calligraphyHint: "Yalnızca Çince ve Rusça",
    writingPlaceholder: "Karakter veya kelime yapıştır",
    createSheet: "Sayfa oluştur",
    card: "Kart",
    of: "/",
    deck: "Deste",
    createAccountHint: "Metinlerini, kelimelerini ve pratiklerini kaydetmek için hesap oluştur.",
    loginToContinue: "Pratik yapmaya başlamak için giriş yap",
    cardsTitle: "Kartlar",
    cardsSubtitle: "Metinlerden yeni kelimeler kaydet veya kendi listeni yükle",
    fcBrowse: "Gözat",
    fcLearnTab: "Öğren",
    fcCheckTab: "Sınav",
    speakTermMode: "Söyle: Kelime",
    speakTranslationMode: "Söyle: Çeviri",
    exitSpeaking: "Konuşmadan çık",
    importWords: "Kelime içe aktar",
    deleteCard: "Kartı sil",
    sayIt: "Söyle",
    practiceAgain: "Tekrar çalış",
    answeredCorrectly: "doğru cevap",
    typedCorrectly: "doğru yazıldı",
    typeTheWord: "Kelimeyi yaz",
    correctAnswerIs: "Doğru cevap:",
    correctExcl: "Doğru!",
    seeResult: "Sonucu gör",
    check: "Kontrol et",
    learnLocked: "Öğren modu için destede en az 5 kart gerekli.",
    noCardsInDeck: "Destede kart yok.",
    comprehensionExercise: "Anlama alıştırması",
    readingTitle: "Okuma",
    sentenceOne: "cümle",
    sentenceMany: "cümle",
    speedHint: "0.75× için kaplumbağaya iki kez dokun",
    rdSetupTitle: "Bugün ne okumak istersin?",
    pasteTextTab: "Metin yapıştır",
    libraryTab: "Kitaplık",
    savedTab: "Kaydedilenler",
    rdSetupPlaceholder: "Buraya bir metin yapıştır — makale, sohbet, şarkı sözü veya ödev. Okunuş, ses ve kelime anlamlarını otomatik ekleriz.",
    charactersLabel: "karakter",
    exerciseWord: "Alıştırma",
    putWordsInOrder: "Kelimeleri sıraya diz",
    chooseMissingWord: "Eksik kelimeyi seç",
    rebuildScrambled: "Karışık cümleyi yeniden kur.",
    whichWordCompletes: "Cümleyi hangi kelime tamamlar?",
    correctOrder: "Doğru sıralama.",
    notQuiteTapBack: "Tam değil — geri göndermek için bir karoya dokun.",
    notQuiteTryAgain: "Tam değil — tekrar dene.",
    completedLabel: "tamamlandı",
    notEnoughText: "Bu alıştırma için yeterli metin yok.",
    listenFirst: "Önce dinle",
    tapToSpeak: "Konuşmak için dokun, bitince tekrar dokun",
    speakNowTapDone: "Şimdi konuş — bitince tekrar dokun",
    scoringLabel: "Puanlanıyor…",
    playingAudio: "Ses çalınıyor…",
    sentenceWord: "Cümle",
    textComplete: "Metin tamamlandı",
    nicelyDone: "Harika!",
    youSpokeAll: "Tüm cümleleri söyledin:",
    sentencesOutLoud: "cümle.",
    overallLabel: "Genel",
    tapToRetrySentence: "Tekrar çalışmak için bir cümleye dokun",
    pasteAnotherText: "Başka metin yapıştır",
    chooseFromLibrary: "Kitaplıktan seç",
    pasteYouTubeLink: "YouTube bağlantısı yapıştır…",
    loadBtn: "Yükle",
    pasteLinkAbove: "Yukarıya bir YouTube bağlantısı yapıştır",
    loadingCaptions: "Altyazılar yükleniyor…",
    noCaptionsTitle: "Altyazı bulunamadı",
    noCaptionsSub: "Video açıldı ama öğrenilen dilde kullanılabilir altyazı bulunamadı.",
    tryAnotherVideo: "Başka bir video dene",
    captionsUnavailable: "Altyazılar geçici olarak kullanılamıyor",
    tryAgain: "Tekrar dene",
    speakThisLine: "Bu satırı söyle",
    translatePill: "Çeviri",
    pinyinPill: "Pinyin",
    romajiPill: "Romaji",
    quotaChecksTitle: "Bugünün ücretsiz kontrolleri bitti",
    quotaChecksSub: "Bugünkü {n} telaffuz kontrolünün hepsini kullandın. Pro ile sınırsız pratik yap.",
    quotaResetTomorrow: "Ücretsiz hakların yarın yenilenir.",
    quotaTextsTitle: "Bugünün ücretsiz metinleri bitti",
    quotaTextsSub: "Bugün {n} metin ekledin. Pro ile istediğin kadar ekle.",
    quotaSavedSub: "{n} metin kaydettin (ücretsiz sınır). Pro ile sınırsız kaydet.",
    quotaLimitTitle: "Ücretsiz sınıra ulaştın",
    quotaDeckSub: "Ücretsiz desteler {n} ile sınırlı. Pro ile sınırsız deste ve kart.",
    quotaCardSub: "Destende {n} kart var (ücretsiz sınır). Pro ile sınırsız kart.",
    quotaVideoTitle: "Videolar bir Pro özelliği",
    quotaVideoSub: "{n} deneme videonu kullandın. Pro ile her videodan öğrenmeye devam et.",
    quotaTtsTitle: "Bugünün ücretsiz sesi bitti",
    quotaTtsSub: "Pro ile sınırsız dinleme — günlük sınır yok.",
    quotaTtsReset: "Ücretsiz ses hakkın yarın yenilenir.",
    quotaTransTitle: "Bugünün ücretsiz çevirileri bitti",
    quotaTransSub: "Pro ile sınırsız çeviri — günlük sınır yok.",
    quotaTransReset: "Ücretsiz çeviri hakkın yarın yenilenir.",
    upgradeDefaultTitle: "Pro'ya geç",
    upgradeDefaultSub: "Pro ile sınırsız erişim.",
    cmpTextsDay: "Metin / gün",
    cmpChecksDay: "Telaffuz kontrolü / gün",
    cmpSavedTexts: "Kayıtlı metinler",
    cmpDecksCards: "Desteler · kartlar",
    cmpVideos: "Altyazılı videolar",
    freeLabel: "Ücretsiz",
    proLabel: "Pro",
    maybeLater: "Belki sonra",
    annualPlanBtn: "Yıllık — 49$/yıl",
    monthlyPlanBtn: "Aylık — 6,99$/ay",
    savePct: "%41 tasarruf",
    freePlanLabel: "Ücretsiz plan",

    saved: "Kaydedildi",
    savedTextsError: "Kaydedilen metinler yüklenemedi.",
    hidePinyin: "Pinyini gizle",
    voice: "Ses",
    voicePickerHeading: "Bu dil için bir ses seç",
    wordSaveHint: "İpucu: herhangi bir kelimeye tıkla, duyabilir, çevirebilir ve kartlara kaydedebilirsin.",
    hideFullText: "Metni gizle",
    showFullText: "Metni göster",
    grammarFailed: "Dilbilgisi kontrolü başarısız.",
    pinyinError: "Pinyin yüklenemedi."
  },

  de: {
getStarted: "Loslegen",
logout: "Abmelden",

authTitle: "Verwandle jeden Text in aktives Lernen",
authSubtitle: "Füge einen Text ein, höre Satz für Satz zu, sprich, übersetze und speichere nützliche Wörter.",
welcomeBack: "Willkommen zurück 👋",
loginHint: "Melde dich an oder erstelle ein Konto, um fortzufahren.",
loginTitle: "Willkommen zurück",
signupTitle: "Kostenloses Konto erstellen",
signupTrialHint: "Starte deine 7-tägige Pro-Testphase. Keine Zahlungsmethode erforderlich.",
name: "Name",
email: "E-Mail",
password: "Passwort",
forgotPassword: "Passwort vergessen?",
login: "Anmelden",
createAccount: "Konto erstellen",
enterEmail: "E-Mail eingeben",
restorePassword: "Passwort zurücksetzen",
createNewPassword: "Bitte erstelle ein neues Passwort.",
passwordTooShort: "Das Passwort muss mindestens 6 Zeichen lang sein.",
savingPassword: "Neues Passwort wird gespeichert...",
loggingIn: "Anmeldung läuft...",
creatingAccount: "Konto wird erstellt...",
enterAllFields: "Bitte Name, E-Mail und Passwort eingeben.",
enterEmailError: "Bitte E-Mail eingeben.",
enterEmailInstruction: "Gib deine E-Mail ein und klicke auf Passwort zurücksetzen.",
sendingRecovery: "Wiederherstellungs-E-Mail wird gesendet...",
recoverySent: "E-Mail gesendet. Bitte überprüfe deinen Posteingang.",
accountCreated: "Konto erstellt. Bitte überprüfe deine E-Mail und melde dich an.",
signupFailed: "Registrierung fehlgeschlagen. Bitte versuche es erneut.",
passwordUpdated: "Passwort aktualisiert.",

welcomeMagic: "Willkommen bei Magic Read",
listenRepeat: "Hören & nachsprechen",
perfectPronunciation: "Trainiere deine Aussprache mit echten Texten",
smartCards: "Wörter speichern",
studyInteractive: "Erstelle Karteikarten aus deinen Texten",
translateLearn: "Schneller verstehen",
understandEverySentence: "Übersetze und lerne Wörter im Kontext",
or: "oder",

library: "Bibliothek",
myTexts: "Meine Texte",
pasteToStart: "Füge einen Text ein, um zu beginnen",
orLibrary: "oder wähle einen Text aus der Bibliothek",
inputPlaceholder: "Füge einen Text ein, um zu beginnen",
start: "Start",
readModeTitle: "Jeden Text lesen und verstehen",
readModeHint: "Füge einen Artikel, eine Geschichte oder eine Lektion ein und erhalte Audio, Übersetzung und Leseübungen.",
startReading: "Lesen starten",
speakModeTitle: "Aussprache mit eigenen Texten üben",
speakModeHint: "Füge Hausaufgaben, Dialoge oder Prüfungstexte ein und erhalte Feedback zu jedem Satz.",
startSpeaking: "Sprechen starten",
trialHeadline: "Pro 7 Tage kostenlos testen",
trialHint: "Erstelle ein kostenloses Konto, um die Testphase zu aktivieren. Keine Zahlungsmethode und keine automatische Abbuchung.",
trialCreateAccount: "Kostenloses Konto erstellen",
trialExploreFree: "Mit kostenlosen Limits testen",
chooseLanguages: "Sprachen auswählen",
changeLanguagesLater: "Du kannst sie später in den Einstellungen ändern.",
iSpeak: "Ich spreche",
imLearning: "Ich lerne",
continue: "Weiter",
trialUnlimitedPronunciation: "Unbegrenzte Ausspracheprüfungen",
trialSmartCaptions: "Videos mit intelligenten Untertiteln",
trialAllDecks: "Alle Karteikarten und Kalligrafie-Export",
lifetimeOffer: "Gründer-Lifetime-Zugang — einmalig $89",
tbankPaymentLabel: "Russische Karte oder SBP",
tbankMonthly: "1 Monat — 600 ₽",
tbankAnnual: "1 Jahr — 5.000 ₽",
tbankPaymentPending: "Zahlung erhalten. Pro wird in Kürze aktiviert.",
tbankPaymentFailed: "Die Zahlung wurde nicht abgeschlossen.",
redirecting: "Weiterleitung…",
saveText: "Text speichern",
    iSpeak: "Ich spreche",
    iLearn: "Ich lerne",
savedTexts: "Meine Texte",
savedTextsTitle: "Meine Texte",

ready: "Bereit ✓",
edit: "Bearbeiten",
replace: "Ersetzen",

fullText: "Gesamter Text",
readComplete: "Lies den vollständigen Text.",
play: "Abspielen",
listen: "Anhören",
listening: "Wird abgespielt…",
pause: "Pause",
slowOff: "Langsam: AUS",
slowOn: "Langsam: EIN",
translate: "Übersetzen",
showTranslation: "Übersetzung anzeigen",
meaning: "Bedeutung",
showPinyin: "Pinyin",
done: "Fertig",

practiceCards: "Übung",
practiceHint: "Höre zu, sprich und speichere nützliche Wörter.",
record: "Du bist dran",
yourTurn: "Du bist dran",
stop: "Stopp",
next: "Weiter",
previous: "Zurück",
skip: "Überspringen",

grammar: "Grammatik",
save: "Speichern",
flashcards: "Karteikarten",

noWords: "Noch keine Wörter",
clickToSave: "Klicke auf ein Wort im Text, um es zu speichern.",
calligraphy: "Kalligraphie",

backToReading: "← Zurück zum Lesen",
newDeck: "Neues Deck",
deleteDeck: "Deck löschen",
clear: "Leeren",
exportPDF: "Als PDF exportieren",
wordLabel: "Wort",
context: "Kontext",
delete: "Löschen",
calligraphyHint: "Nur Chinesisch und Russisch",
writingPlaceholder: "Zeichen oder Wörter einfügen",
createSheet: "Übungsblatt erstellen",
card: "Karte",
of: "von",
deck: "Deck",
createAccountHint: "Erstelle ein Konto, um Texte, Vokabeln und Übungen zu speichern.",
loginToContinue: "Melde dich an, um mit dem Üben zu beginnen",
cardsTitle: "Karten",
cardsSubtitle: "Speichere neue Wörter aus Texten oder lade deine eigene Liste hoch",
fcBrowse: "Blättern",
fcLearnTab: "Lernen",
fcCheckTab: "Prüfen",
speakTermMode: "Sprechen: Wort",
speakTranslationMode: "Sprechen: Übersetzung",
exitSpeaking: "Sprechen beenden",
importWords: "Wörter importieren",
deleteCard: "Karte löschen",
sayIt: "Sprich es",
practiceAgain: "Nochmal üben",
answeredCorrectly: "richtig beantwortet",
typedCorrectly: "richtig getippt",
typeTheWord: "Wort eintippen",
correctAnswerIs: "Richtige Antwort:",
correctExcl: "Richtig!",
seeResult: "Ergebnis ansehen",
check: "Prüfen",
learnLocked: "Lernen braucht mindestens 5 Karten im Stapel.",
noCardsInDeck: "Keine Karten im Stapel.",
comprehensionExercise: "Verständnisübung",
readingTitle: "Lesen",
sentenceOne: "Satz",
sentenceMany: "Sätze",
speedHint: "Zweimal auf die Schildkröte tippen für 0,75×",
rdSetupTitle: "Was möchtest du heute lesen?",
pasteTextTab: "Text einfügen",
libraryTab: "Bibliothek",
savedTab: "Gespeichert",
rdSetupPlaceholder: "Füge hier einen Text ein — Artikel, Chat, Songtext oder Hausaufgabe. Wir ergänzen automatisch Umschrift, Audio und Wortbedeutungen.",
charactersLabel: "Zeichen",
exerciseWord: "Übung",
putWordsInOrder: "Bringe die Wörter in die richtige Reihenfolge",
chooseMissingWord: "Wähle das fehlende Wort",
rebuildScrambled: "Setze den Satz wieder zusammen.",
whichWordCompletes: "Welches Wort vervollständigt den Satz?",
correctOrder: "Richtige Reihenfolge.",
notQuiteTapBack: "Nicht ganz — tippe auf eine Kachel, um sie zurückzulegen.",
notQuiteTryAgain: "Nicht ganz — versuch's nochmal.",
completedLabel: "abgeschlossen",
notEnoughText: "Nicht genug Text für diese Übung.",
listenFirst: "Erst anhören",
tapToSpeak: "Zum Sprechen tippen, danach erneut tippen",
speakNowTapDone: "Sprich jetzt — tippe erneut, wenn du fertig bist",
scoringLabel: "Bewertung…",
playingAudio: "Audio läuft…",
sentenceWord: "Satz",
textComplete: "Text geschafft",
nicelyDone: "Gut gemacht!",
youSpokeAll: "Du hast alle gesprochen:",
sentencesOutLoud: "Sätze laut.",
overallLabel: "Gesamt",
tapToRetrySentence: "Tippe auf einen Satz, um ihn erneut zu üben",
pasteAnotherText: "Anderen Text einfügen",
chooseFromLibrary: "Aus der Bibliothek wählen",
pasteYouTubeLink: "YouTube-Link einfügen…",
loadBtn: "Laden",
pasteLinkAbove: "Füge oben einen YouTube-Link ein",
loadingCaptions: "Untertitel werden geladen…",
noCaptionsTitle: "Keine Untertitel gefunden",
noCaptionsSub: "Das Video wurde geöffnet, aber es gibt keine passenden Untertitel in der Lernsprache.",
tryAnotherVideo: "Anderes Video versuchen",
captionsUnavailable: "Untertitel vorübergehend nicht verfügbar",
tryAgain: "Erneut versuchen",
speakThisLine: "Diesen Satz sprechen",
translatePill: "Übersetzung",
pinyinPill: "Pinyin",
romajiPill: "Romaji",
quotaChecksTitle: "Deine kostenlosen Checks für heute sind aufgebraucht",
quotaChecksSub: "Du hast alle {n} Aussprache-Checks für heute genutzt. Mit Pro übst du unbegrenzt — ohne Tageslimit.",
quotaResetTomorrow: "Deine kostenlosen Checks gibt es morgen wieder.",
quotaTextsTitle: "Das waren deine Gratis-Texte für heute",
quotaTextsSub: "Du hast heute {n} Texte hinzugefügt. Mit Pro so viele du willst.",
quotaSavedSub: "Du hast {n} Texte gespeichert (Gratis-Limit). Mit Pro unbegrenzt.",
quotaLimitTitle: "Du hast das Gratis-Limit erreicht",
quotaDeckSub: "Gratis sind maximal {n} Stapel. Mit Pro unbegrenzt Stapel und Karten.",
quotaCardSub: "Dein Stapel hat {n} Karten (Gratis-Limit). Mit Pro unbegrenzt.",
quotaVideoTitle: "Videos sind ein Pro-Feature",
quotaVideoSub: "Du hast deine {n} Test-Videos genutzt. Mit Pro lernst du mit jedem Video weiter.",
quotaTtsTitle: "Dein Gratis-Audio für heute ist aufgebraucht",
quotaTtsSub: "Mit Pro hörst du unbegrenzt — ohne Tageslimit.",
quotaTtsReset: "Dein Gratis-Audio gibt es morgen wieder.",
quotaTransTitle: "Deine Gratis-Übersetzungen für heute sind aufgebraucht",
quotaTransSub: "Mit Pro übersetzt du unbegrenzt — ohne Tageslimit.",
quotaTransReset: "Deine Gratis-Übersetzungen gibt es morgen wieder.",
upgradeDefaultTitle: "Auf Pro upgraden",
upgradeDefaultSub: "Mit Pro hast du unbegrenzten Zugriff.",
cmpTextsDay: "Texte / Tag",
cmpChecksDay: "Aussprache-Checks / Tag",
cmpSavedTexts: "Gespeicherte Texte",
cmpDecksCards: "Stapel · Karten",
cmpVideos: "Videos mit Untertiteln",
freeLabel: "Free",
proLabel: "Pro",
maybeLater: "Vielleicht später",
annualPlanBtn: "Jährlich — 49 $/Jahr",
monthlyPlanBtn: "Monatlich — 6,99 $/Monat",
savePct: "41 % sparen",
freePlanLabel: "Gratis-Plan",

saved: "Gespeichert",
savedTextsError: "Texte konnten nicht geladen werden.",
hidePinyin: "Pinyin ausblenden",
voice: "Stimme",
voicePickerHeading: "Stimme für diese Sprache wählen",
wordSaveHint: "Tipp: Klicke auf ein Wort, um es anzuhören, zu übersetzen und zu speichern.",
hideFullText: "Text ausblenden",
showFullText: "Text einblenden",
grammarFailed: "Grammatikprüfung fehlgeschlagen.",
pinyinError: "Pinyin konnte nicht geladen werden."
},

es: {
getStarted: "Comenzar",
logout: "Cerrar sesión",

authTitle: "Convierte cualquier texto en práctica activa",
authSubtitle: "Pega un texto, escucha frase por frase, habla, traduce y guarda palabras útiles.",
welcomeBack: "Bienvenido de nuevo 👋",
loginHint: "Inicia sesión o crea una cuenta para continuar.",
loginTitle: "Bienvenido de nuevo",
signupTitle: "Crea tu cuenta gratuita",
signupTrialHint: "Inicia tu prueba Pro de 7 días. No se requiere método de pago.",
name: "Nombre",
email: "Correo electrónico",
password: "Contraseña",
forgotPassword: "¿Olvidaste tu contraseña?",
login: "Iniciar sesión",
createAccount: "Crear cuenta",
enterEmail: "Introduce tu correo",
restorePassword: "Restablecer contraseña",
createNewPassword: "Por favor crea una nueva contraseña.",
passwordTooShort: "La contraseña debe tener al menos 6 caracteres.",
savingPassword: "Guardando nueva contraseña...",
loggingIn: "Iniciando sesión...",
creatingAccount: "Creando cuenta...",
enterAllFields: "Por favor introduce nombre, correo y contraseña.",
enterEmailError: "Por favor introduce tu correo.",
enterEmailInstruction: "Introduce tu correo y haz clic en restablecer contraseña.",
sendingRecovery: "Enviando correo de recuperación...",
recoverySent: "Correo enviado. Revisa tu bandeja de entrada.",
accountCreated: "Cuenta creada. Revisa tu correo e inicia sesión.",
signupFailed: "Error al registrarse. Inténtalo de nuevo.",
passwordUpdated: "Contraseña actualizada.",

welcomeMagic: "Bienvenido a Magic Read",
listenRepeat: "Escucha y repite",
perfectPronunciation: "Practica pronunciación con textos reales",
smartCards: "Guardar palabras",
studyInteractive: "Crea tarjetas desde lo que lees",
translateLearn: "Comprende más rápido",
understandEverySentence: "Traduce y aprende palabras en contexto",
or: "o",

library: "Biblioteca",
myTexts: "Mis textos",
pasteToStart: "Pega un texto para comenzar",
orLibrary: "o elige un texto de la biblioteca",
inputPlaceholder: "Pega un texto para comenzar",
start: "Comenzar",
readModeTitle: "Lee y comprende cualquier texto",
readModeHint: "Pega un artículo, historia o lección para obtener audio, traducción y ejercicios de lectura.",
startReading: "Empezar a leer",
speakModeTitle: "Practica pronunciación con tus propios textos",
speakModeHint: "Pega tareas, diálogos o textos de examen y recibe comentarios frase por frase.",
startSpeaking: "Empezar a hablar",
trialHeadline: "Prueba Pro gratis durante 7 días",
trialHint: "Crea una cuenta gratuita para activar la prueba. No requiere método de pago ni se cobrará automáticamente.",
trialCreateAccount: "Crear cuenta gratuita",
trialExploreFree: "Explorar con límites gratuitos",
chooseLanguages: "Elige idiomas",
changeLanguagesLater: "Puedes cambiarlos más tarde en los ajustes.",
iSpeak: "Hablo",
imLearning: "Estoy aprendiendo",
continue: "Continuar",
trialUnlimitedPronunciation: "Evaluaciones de pronunciación ilimitadas",
trialSmartCaptions: "Vídeos con subtítulos inteligentes",
trialAllDecks: "Todas las tarjetas y exportación de caligrafía",
lifetimeOffer: "Acceso de por vida para fundadores — $89 una vez",
tbankPaymentLabel: "Tarjeta rusa o SBP",
tbankMonthly: "1 mes — 600 ₽",
tbankAnnual: "1 año — 5.000 ₽",
tbankPaymentPending: "Pago recibido. El acceso Pro aparecerá en breve.",
tbankPaymentFailed: "El pago no se completó.",
redirecting: "Redirigiendo…",
saveText: "Guardar texto",
    iSpeak: "Hablo",
    iLearn: "Aprendo",
savedTexts: "Mis textos",
savedTextsTitle: "Mis textos",

ready: "Listo ✓",
edit: "Editar",
replace: "Reemplazar",

fullText: "Texto completo",
readComplete: "Lee el texto completo.",
play: "Reproducir",
listen: "Escuchar",
listening: "Escuchando…",
pause: "Pausa",
slowOff: "Lento: OFF",
slowOn: "Lento: ON",
translate: "Traducir",
showTranslation: "Mostrar traducción",
meaning: "Significado",
showPinyin: "Pinyin",
done: "Hecho",

practiceCards: "Práctica",
practiceHint: "Escucha, habla y guarda palabras útiles.",
record: "Tu turno",
yourTurn: "Tu turno",
stop: "Detener",
next: "Siguiente",
previous: "Anterior",
skip: "Saltar",

grammar: "Gramática",
save: "Guardar",
flashcards: "Tarjetas",

noWords: "Todavía no hay palabras",
clickToSave: "Haz clic en cualquier palabra para guardarla.",
calligraphy: "Caligrafía",

backToReading: "← Volver a la lectura",
newDeck: "Nueva baraja",
deleteDeck: "Eliminar baraja",
clear: "Vaciar",
exportPDF: "Exportar PDF",
wordLabel: "Palabra",
context: "Contexto",
delete: "Eliminar",
calligraphyHint: "Solo chino y ruso",
writingPlaceholder: "Pega caracteres o palabras",
createSheet: "Crear hoja",
card: "Tarjeta",
of: "de",
deck: "Baraja",
createAccountHint: "Crea una cuenta para guardar tus textos, vocabulario y práctica.",
loginToContinue: "Inicia sesión para empezar a practicar",
cardsTitle: "Tarjetas",
cardsSubtitle: "Guarda palabras nuevas de los textos o sube tu propia lista",
fcBrowse: "Explorar",
fcLearnTab: "Aprender",
fcCheckTab: "Examen",
speakTermMode: "Pronunciar: palabra",
speakTranslationMode: "Pronunciar: traducción",
exitSpeaking: "Salir de práctica",
importWords: "Importar palabras",
deleteCard: "Eliminar tarjeta",
sayIt: "Dilo",
practiceAgain: "Practicar de nuevo",
answeredCorrectly: "respuestas correctas",
typedCorrectly: "escritas correctamente",
typeTheWord: "Escribe la palabra",
correctAnswerIs: "Respuesta correcta:",
correctExcl: "¡Correcto!",
seeResult: "Ver resultado",
check: "Comprobar",
learnLocked: "Aprender necesita al menos 5 tarjetas en el mazo.",
noCardsInDeck: "No hay tarjetas en el mazo.",
comprehensionExercise: "Ejercicio de comprensión",
readingTitle: "Lectura",
sentenceOne: "frase",
sentenceMany: "frases",
speedHint: "Toca la tortuga dos veces para 0,75×",
rdSetupTitle: "¿Qué te gustaría leer hoy?",
pasteTextTab: "Pegar texto",
libraryTab: "Biblioteca",
savedTab: "Guardados",
rdSetupPlaceholder: "Pega aquí un texto: un artículo, un chat, la letra de una canción o los deberes. Añadimos transcripción, audio y significados automáticamente.",
charactersLabel: "caracteres",
exerciseWord: "Ejercicio",
putWordsInOrder: "Ordena las palabras",
chooseMissingWord: "Elige la palabra que falta",
rebuildScrambled: "Reconstruye la frase desordenada.",
whichWordCompletes: "¿Qué palabra completa la frase?",
correctOrder: "Orden correcto.",
notQuiteTapBack: "No exactamente: toca una ficha para devolverla.",
notQuiteTryAgain: "No exactamente: inténtalo de nuevo.",
completedLabel: "completado",
notEnoughText: "No hay texto suficiente para este ejercicio.",
listenFirst: "Escuchar primero",
tapToSpeak: "Toca para hablar y de nuevo al terminar",
speakNowTapDone: "Habla ahora: toca de nuevo al terminar",
scoringLabel: "Evaluando…",
playingAudio: "Reproduciendo…",
sentenceWord: "Frase",
textComplete: "Texto completado",
nicelyDone: "¡Bien hecho!",
youSpokeAll: "Has leído en voz alta las",
sentencesOutLoud: "frases en voz alta.",
overallLabel: "Total",
tapToRetrySentence: "Toca una frase para practicarla de nuevo",
pasteAnotherText: "Pegar otro texto",
chooseFromLibrary: "Elegir de la biblioteca",
pasteYouTubeLink: "Pega un enlace de YouTube…",
loadBtn: "Cargar",
pasteLinkAbove: "Pega arriba un enlace de YouTube",
loadingCaptions: "Cargando subtítulos…",
noCaptionsTitle: "No hay subtítulos",
noCaptionsSub: "El vídeo se abrió, pero no encontramos subtítulos en el idioma que aprendes.",
tryAnotherVideo: "Prueba otro vídeo",
captionsUnavailable: "Subtítulos no disponibles temporalmente",
tryAgain: "Intentar de nuevo",
speakThisLine: "Pronuncia esta línea",
translatePill: "Traducción",
pinyinPill: "Pinyin",
romajiPill: "Romaji",
quotaChecksTitle: "Se acabaron tus revisiones gratis de hoy",
quotaChecksSub: "Has usado las {n} revisiones de pronunciación de hoy. Con Pro practicas sin límite diario.",
quotaResetTomorrow: "Tus revisiones gratis se renuevan mañana.",
quotaTextsTitle: "Esos son tus textos gratis de hoy",
quotaTextsSub: "Has añadido {n} textos hoy. Con Pro, todos los que quieras.",
quotaSavedSub: "Has guardado {n} textos (límite gratis). Con Pro, sin límite.",
quotaLimitTitle: "Has alcanzado el límite gratis",
quotaDeckSub: "Los mazos gratis se limitan a {n}. Con Pro, mazos y tarjetas sin límite.",
quotaCardSub: "Tu mazo tiene {n} tarjetas (límite gratis). Con Pro, sin límite.",
quotaVideoTitle: "Los vídeos son una función Pro",
quotaVideoSub: "Has usado tus {n} vídeos de prueba. Con Pro sigue aprendiendo con cualquier vídeo.",
quotaTtsTitle: "Has usado el audio gratis de hoy",
quotaTtsSub: "Con Pro escuchas sin límite diario.",
quotaTtsReset: "Tu audio gratis se renueva mañana.",
quotaTransTitle: "Has usado las traducciones gratis de hoy",
quotaTransSub: "Con Pro traduces sin límite diario.",
quotaTransReset: "Tus traducciones gratis se renuevan mañana.",
upgradeDefaultTitle: "Pásate a Pro",
upgradeDefaultSub: "Con Pro tienes acceso ilimitado.",
cmpTextsDay: "Textos / día",
cmpChecksDay: "Revisiones / día",
cmpSavedTexts: "Textos guardados",
cmpDecksCards: "Mazos · tarjetas",
cmpVideos: "Vídeos con subtítulos",
freeLabel: "Gratis",
proLabel: "Pro",
maybeLater: "Quizá luego",
annualPlanBtn: "Anual — 49 $/año",
monthlyPlanBtn: "Mensual — 6,99 $/mes",
savePct: "Ahorra un 41 %",
freePlanLabel: "Plan gratis",

saved: "Guardada",
savedTextsError: "No se pudieron cargar los textos guardados.",
hidePinyin: "Ocultar pinyin",
voice: "Voz",
voicePickerHeading: "Elige una voz para este idioma",
wordSaveHint: "Consejo: haz clic en cualquier palabra para escucharla, traducirla y guardarla.",
hideFullText: "Ocultar texto",
showFullText: "Mostrar texto",
grammarFailed: "Error al revisar la gramática.",
pinyinError: "No se pudo cargar el pinyin."
},

fr: {
getStarted: "Commencer",
logout: "Se déconnecter",

authTitle: "Transformez n’importe quel texte en pratique active",
authSubtitle: "Collez un texte, écoutez phrase par phrase, parlez, traduisez et sauvegardez des mots utiles.",
welcomeBack: "Bon retour 👋",
loginHint: "Connectez-vous ou créez un compte pour continuer.",
loginTitle: "Bon retour",
signupTitle: "Créez votre compte gratuit",
signupTrialHint: "Démarrez votre essai Pro de 7 jours. Aucun moyen de paiement requis.",
name: "Nom",
email: "E-mail",
password: "Mot de passe",
forgotPassword: "Mot de passe oublié ?",
login: "Se connecter",
createAccount: "Créer un compte",
enterEmail: "Entrez votre e-mail",
restorePassword: "Réinitialiser le mot de passe",
createNewPassword: "Veuillez créer un nouveau mot de passe.",
passwordTooShort: "Le mot de passe doit contenir au moins 6 caractères.",
savingPassword: "Enregistrement du nouveau mot de passe...",
loggingIn: "Connexion en cours...",
creatingAccount: "Création du compte...",
enterAllFields: "Veuillez entrer votre nom, e-mail et mot de passe.",
enterEmailError: "Veuillez entrer votre e-mail.",
enterEmailInstruction: "Entrez votre e-mail et cliquez sur réinitialiser le mot de passe.",
sendingRecovery: "Envoi de l’e-mail de récupération...",
recoverySent: "E-mail envoyé. Vérifiez votre boîte de réception.",
accountCreated: "Compte créé. Vérifiez votre e-mail puis connectez-vous.",
signupFailed: "Échec de l’inscription. Veuillez réessayer.",
passwordUpdated: "Mot de passe mis à jour.",

welcomeMagic: "Bienvenue sur Magic Read",
listenRepeat: "Écouter et répéter",
perfectPronunciation: "Travaillez votre prononciation avec de vrais textes",
smartCards: "Sauvegarder des mots",
studyInteractive: "Créez des cartes mémoire à partir de vos lectures",
translateLearn: "Comprendre plus vite",
understandEverySentence: "Traduisez et apprenez les mots en contexte",
or: "ou",

library: "Bibliothèque",
myTexts: "Mes textes",
pasteToStart: "Collez un texte pour commencer",
orLibrary: "ou choisissez un texte dans la bibliothèque",
inputPlaceholder: "Collez un texte pour commencer",
start: "Commencer",
readModeTitle: "Lisez et comprenez n’importe quel texte",
readModeHint: "Collez un article, une histoire ou une leçon pour obtenir l’audio, la traduction et des exercices de lecture.",
startReading: "Commencer à lire",
speakModeTitle: "Travaillez la prononciation avec vos propres textes",
speakModeHint: "Collez un devoir, un dialogue ou un texte d’examen et recevez un retour phrase par phrase.",
startSpeaking: "Commencer à parler",
trialHeadline: "Essayez Pro gratuitement pendant 7 jours",
trialHint: "Créez un compte gratuit pour activer l’essai. Aucun moyen de paiement et aucun prélèvement automatique.",
trialCreateAccount: "Créer un compte gratuit",
trialExploreFree: "Explorer avec les limites gratuites",
chooseLanguages: "Choisissez les langues",
changeLanguagesLater: "Vous pourrez les modifier plus tard dans les réglages.",
iSpeak: "Je parle",
imLearning: "J’apprends",
continue: "Continuer",
trialUnlimitedPronunciation: "Évaluations de prononciation illimitées",
trialSmartCaptions: "Vidéos avec sous-titres intelligents",
trialAllDecks: "Toutes les cartes et export de calligraphie",
lifetimeOffer: "Accès à vie fondateur — 89 $ une fois",
tbankPaymentLabel: "Carte russe ou SBP",
tbankMonthly: "1 mois — 600 ₽",
tbankAnnual: "1 an — 5 000 ₽",
tbankPaymentPending: "Paiement reçu. L’accès Pro sera bientôt activé.",
tbankPaymentFailed: "Le paiement n’a pas été finalisé.",
redirecting: "Redirection…",
saveText: "Sauvegarder le texte",
    iSpeak: "Je parle",
    iLearn: "J'apprends",
savedTexts: "Mes textes",
savedTextsTitle: "Mes textes",

ready: "Prêt ✓",
edit: "Modifier",
replace: "Remplacer",

fullText: "Texte complet",
readComplete: "Lisez le texte complet.",
play: "Lire",
listen: "Écouter",
listening: "Lecture…",
pause: "Pause",
slowOff: "Lent : OFF",
slowOn: "Lent : ON",
translate: "Traduire",
showTranslation: "Afficher la traduction",
meaning: "Signification",
showPinyin: "Pinyin",
done: "Terminé",

practiceCards: "Pratique",
practiceHint: "Écoutez, parlez et sauvegardez des mots utiles.",
record: "À vous",
yourTurn: "À vous",
stop: "Arrêter",
next: "Suivant",
previous: "Précédent",
skip: "Passer",

grammar: "Grammaire",
save: "Sauvegarder",
flashcards: "Cartes mémoire",

noWords: "Pas encore de mots",
clickToSave: "Cliquez sur un mot pour le sauvegarder.",
calligraphy: "Calligraphie",

backToReading: "← Retour à la lecture",
newDeck: "Nouveau paquet",
deleteDeck: "Supprimer le paquet",
clear: "Vider",
exportPDF: "Exporter en PDF",
wordLabel: "Mot",
context: "Contexte",
delete: "Supprimer",
calligraphyHint: "Chinois et russe uniquement",
writingPlaceholder: "Collez des caractères ou des mots",
createSheet: "Créer une fiche",
card: "Carte",
of: "sur",
deck: "Paquet",
createAccountHint: "Créez un compte pour sauvegarder vos textes, vocabulaire et pratique.",
loginToContinue: "Connectez-vous pour commencer à pratiquer",
cardsTitle: "Cartes",
cardsSubtitle: "Enregistrez de nouveaux mots depuis les textes ou importez votre liste",
fcBrowse: "Parcourir",
fcLearnTab: "Apprendre",
fcCheckTab: "Contrôle",
speakTermMode: "Prononcer : mot",
speakTranslationMode: "Prononcer : traduction",
exitSpeaking: "Quitter l'exercice",
importWords: "Importer des mots",
deleteCard: "Supprimer la carte",
sayIt: "Dites-le",
practiceAgain: "Recommencer",
answeredCorrectly: "bonnes réponses",
typedCorrectly: "bien saisies",
typeTheWord: "Saisissez le mot",
correctAnswerIs: "Bonne réponse :",
correctExcl: "Correct !",
seeResult: "Voir le résultat",
check: "Vérifier",
learnLocked: "Apprendre nécessite au moins 5 cartes dans le paquet.",
noCardsInDeck: "Aucune carte dans le paquet.",
comprehensionExercise: "Exercice de compréhension",
readingTitle: "Lecture",
sentenceOne: "phrase",
sentenceMany: "phrases",
speedHint: "Touchez deux fois la tortue pour 0,75×",
rdSetupTitle: "Que voulez-vous lire aujourd'hui ?",
pasteTextTab: "Coller un texte",
libraryTab: "Bibliothèque",
savedTab: "Enregistrés",
rdSetupPlaceholder: "Collez un texte ici — un article, une discussion, des paroles ou un devoir. Nous ajoutons la transcription, l'audio et le sens des mots automatiquement.",
charactersLabel: "caractères",
exerciseWord: "Exercice",
putWordsInOrder: "Remettez les mots dans l'ordre",
chooseMissingWord: "Choisissez le mot manquant",
rebuildScrambled: "Reconstituez la phrase mélangée.",
whichWordCompletes: "Quel mot complète la phrase ?",
correctOrder: "Bon ordre.",
notQuiteTapBack: "Pas tout à fait — touchez une tuile pour la renvoyer.",
notQuiteTryAgain: "Pas tout à fait — réessayez.",
completedLabel: "terminé",
notEnoughText: "Pas assez de texte pour cet exercice.",
listenFirst: "Écouter d'abord",
tapToSpeak: "Touchez pour parler, retouchez quand vous avez fini",
speakNowTapDone: "Parlez — retouchez quand vous avez fini",
scoringLabel: "Évaluation…",
playingAudio: "Lecture audio…",
sentenceWord: "Phrase",
textComplete: "Texte terminé",
nicelyDone: "Bien joué !",
youSpokeAll: "Vous avez prononcé les",
sentencesOutLoud: "phrases à voix haute.",
overallLabel: "Global",
tapToRetrySentence: "Touchez une phrase pour la retravailler",
pasteAnotherText: "Coller un autre texte",
chooseFromLibrary: "Choisir dans la bibliothèque",
pasteYouTubeLink: "Collez un lien YouTube…",
loadBtn: "Charger",
pasteLinkAbove: "Collez un lien YouTube ci-dessus",
loadingCaptions: "Chargement des sous-titres…",
noCaptionsTitle: "Aucun sous-titre trouvé",
noCaptionsSub: "La vidéo s'est ouverte, mais aucun sous-titre exploitable dans la langue apprise.",
tryAnotherVideo: "Essayer une autre vidéo",
captionsUnavailable: "Sous-titres temporairement indisponibles",
tryAgain: "Réessayer",
speakThisLine: "Prononcer cette ligne",
translatePill: "Traduction",
pinyinPill: "Pinyin",
romajiPill: "Romaji",
quotaChecksTitle: "Vos vérifications gratuites du jour sont épuisées",
quotaChecksSub: "Vous avez utilisé vos {n} vérifications du jour. Avec Pro, pratiquez sans limite quotidienne.",
quotaResetTomorrow: "Vos vérifications gratuites reviennent demain.",
quotaTextsTitle: "Vos textes gratuits du jour sont épuisés",
quotaTextsSub: "Vous avez ajouté {n} textes aujourd'hui. Avec Pro, autant que vous voulez.",
quotaSavedSub: "Vous avez enregistré {n} textes (limite gratuite). Avec Pro, sans limite.",
quotaLimitTitle: "Vous avez atteint la limite gratuite",
quotaDeckSub: "Les paquets gratuits sont limités à {n}. Avec Pro, paquets et cartes illimités.",
quotaCardSub: "Votre paquet a {n} cartes (limite gratuite). Avec Pro, cartes illimitées.",
quotaVideoTitle: "Les vidéos sont une fonction Pro",
quotaVideoSub: "Vous avez utilisé vos {n} vidéos d'essai. Avec Pro, apprenez avec n'importe quelle vidéo.",
quotaTtsTitle: "Votre audio gratuit du jour est épuisé",
quotaTtsSub: "Avec Pro, écoutez sans limite quotidienne.",
quotaTtsReset: "Votre audio gratuit revient demain.",
quotaTransTitle: "Vos traductions gratuites du jour sont épuisées",
quotaTransSub: "Avec Pro, traduisez sans limite quotidienne.",
quotaTransReset: "Vos traductions gratuites reviennent demain.",
upgradeDefaultTitle: "Passez à Pro",
upgradeDefaultSub: "Avec Pro, accès illimité.",
cmpTextsDay: "Textes / jour",
cmpChecksDay: "Vérifications / jour",
cmpSavedTexts: "Textes enregistrés",
cmpDecksCards: "Paquets · cartes",
cmpVideos: "Vidéos sous-titrées",
freeLabel: "Gratuit",
proLabel: "Pro",
maybeLater: "Peut-être plus tard",
annualPlanBtn: "Annuel — 49 $/an",
monthlyPlanBtn: "Mensuel — 6,99 $/mois",
savePct: "-41 %",
freePlanLabel: "Offre gratuite",

saved: "Sauvegardé",
savedTextsError: "Impossible de charger les textes sauvegardés.",
hidePinyin: "Masquer le pinyin",
voice: "Voix",
voicePickerHeading: "Choisissez une voix pour cette langue",
wordSaveHint: "Astuce : cliquez sur un mot pour l'écouter, le traduire et le sauvegarder.",
hideFullText: "Masquer le texte",
showFullText: "Afficher le texte",
grammarFailed: "Échec de la vérification grammaticale.",
pinyinError: "Impossible de charger le pinyin."
},

ja: {
getStarted: "始める",
logout: "ログアウト",

authTitle: "どんなテキストもアクティブな練習に変える",
authSubtitle: "テキストを貼り付けて、文ごとに聞き、話し、翻訳し、便利な単語を保存しましょう。",
welcomeBack: "おかえりなさい 👋",
loginHint: "続けるにはログインするか、アカウントを作成してください。",
loginTitle: "おかえりなさい",
signupTitle: "無料アカウントを作成",
signupTrialHint: "7日間のProトライアルを開始。お支払い方法は不要です。",
name: "名前",
email: "メール",
password: "パスワード",
forgotPassword: "パスワードを忘れましたか？",
login: "ログイン",
createAccount: "アカウント作成",
enterEmail: "メールアドレスを入力",
restorePassword: "パスワードをリセット",
createNewPassword: "新しいパスワードを作成してください。",
passwordTooShort: "パスワードは6文字以上にしてください。",
savingPassword: "新しいパスワードを保存中...",
loggingIn: "ログイン中...",
creatingAccount: "アカウントを作成中...",
enterAllFields: "名前、メール、パスワードを入力してください。",
enterEmailError: "メールアドレスを入力してください。",
enterEmailInstruction: "メールアドレスを入力して、パスワードをリセットしてください。",
sendingRecovery: "パスワード再設定メールを送信中...",
recoverySent: "メールを送信しました。受信箱を確認してください。",
accountCreated: "アカウントを作成しました。メールを確認してからログインしてください。",
signupFailed: "登録に失敗しました。もう一度お試しください。",
passwordUpdated: "パスワードを更新しました。",

welcomeMagic: "Magic Readへようこそ",
listenRepeat: "聞いて繰り返す",
perfectPronunciation: "実際のテキストで発音を練習",
smartCards: "単語を保存",
studyInteractive: "読んだ内容から単語カードを作成",
translateLearn: "より速く理解",
understandEverySentence: "文脈の中で単語を翻訳して学ぶ",
or: "または",

library: "ライブラリ",
myTexts: "マイテキスト",
pasteToStart: "テキストを貼り付けて開始",
orLibrary: "またはライブラリからテキストを選択",
inputPlaceholder: "テキストを貼り付けて開始",
start: "開始",
readModeTitle: "どんなテキストも読んで理解する",
readModeHint: "記事、物語、レッスンを貼り付けて、音声、翻訳、読解練習を利用できます。",
startReading: "読解を始める",
speakModeTitle: "自分のテキストで発音を練習",
speakModeHint: "宿題、会話、試験文を貼り付けて、文ごとのスピーキング評価を受けられます。",
startSpeaking: "スピーキングを始める",
trialHeadline: "Proを7日間無料で試す",
trialHint: "無料アカウントを作成してトライアルを有効にします。お支払い方法は不要で、自動課金もありません。",
trialCreateAccount: "無料アカウントを作成",
trialExploreFree: "無料枠で試す",
chooseLanguages: "言語を選択",
changeLanguagesLater: "後で設定から変更できます。",
iSpeak: "話せる言語",
imLearning: "学習中の言語",
continue: "続ける",
trialUnlimitedPronunciation: "発音評価が無制限",
trialSmartCaptions: "スマート字幕付き動画",
trialAllDecks: "すべての単語カードと書写シート出力",
lifetimeOffer: "創設ユーザー向け永久アクセス — 89ドル一括",
tbankPaymentLabel: "ロシア発行カードまたはSBP",
tbankMonthly: "1か月 — 600 ₽",
tbankAnnual: "1年 — 5,000 ₽",
tbankPaymentPending: "支払いを受け付けました。まもなくProが有効になります。",
tbankPaymentFailed: "支払いは完了しませんでした。",
redirecting: "移動しています…",
saveText: "テキストを保存",
    iSpeak: "話せる言語",
    iLearn: "学習中の言語",
savedTexts: "マイテキスト",
savedTextsTitle: "マイテキスト",

ready: "準備完了 ✓",
edit: "編集",
replace: "置き換え",

fullText: "全文",
readComplete: "全文を読みましょう。",
play: "再生",
listen: "聞く",
listening: "聞いています…",
pause: "一時停止",
slowOff: "ゆっくり：オフ",
slowOn: "ゆっくり：オン",
translate: "翻訳",
showTranslation: "翻訳を表示",
meaning: "意味",
showPinyin: "読み方",
done: "完了",

practiceCards: "練習",
practiceHint: "聞いて、話して、便利な単語を保存しましょう。",
record: "あなたの番",
yourTurn: "あなたの番",
stop: "停止",
next: "次へ",
previous: "前へ",
skip: "スキップ",

grammar: "文法",
save: "保存",
flashcards: "単語カード",

noWords: "まだ単語がありません",
clickToSave: "テキスト内の単語をクリックして保存できます。",
calligraphy: "書き取り",

backToReading: "← 読書に戻る",
newDeck: "新しいデッキ",
deleteDeck: "デッキを削除",
clear: "クリア",
exportPDF: "PDFで出力",
wordLabel: "単語",
context: "文脈",
delete: "削除",
calligraphyHint: "中国語とロシア語のみ",
writingPlaceholder: "文字や単語を貼り付けてください",
createSheet: "練習シートを作成",
card: "カード",
of: "/",
deck: "デッキ",
createAccountHint: "テキスト、単語、練習を保存するにはアカウントを作成してください。",
loginToContinue: "練習を始めるにはログインしてください",
cardsTitle: "カード",
cardsSubtitle: "テキストから新しい単語を保存するか、自分のリストをアップロード",
fcBrowse: "一覧",
fcLearnTab: "学習",
fcCheckTab: "チェック",
speakTermMode: "発音：単語",
speakTranslationMode: "発音：翻訳",
exitSpeaking: "発音練習を終了",
importWords: "単語をインポート",
deleteCard: "カードを削除",
sayIt: "言ってみて",
practiceAgain: "もう一度練習",
answeredCorrectly: "正解",
typedCorrectly: "正しく入力",
typeTheWord: "単語を入力",
correctAnswerIs: "正解：",
correctExcl: "正解！",
seeResult: "結果を見る",
check: "チェック",
learnLocked: "学習モードにはデッキに5枚以上のカードが必要です。",
noCardsInDeck: "デッキにカードがありません。",
comprehensionExercise: "理解度エクササイズ",
readingTitle: "読書",
sentenceOne: "文",
sentenceMany: "文",
speedHint: "カメを2回タップで0.75×",
rdSetupTitle: "今日は何を読みますか？",
pasteTextTab: "テキストを貼り付け",
libraryTab: "ライブラリ",
savedTab: "保存済み",
rdSetupPlaceholder: "ここにテキストを貼り付け——記事、チャット、歌詞、宿題など。読み方・音声・単語の意味を自動で追加します。",
charactersLabel: "文字",
exerciseWord: "エクササイズ",
putWordsInOrder: "単語を並べ替え",
chooseMissingWord: "抜けている単語を選択",
rebuildScrambled: "バラバラの文を組み立てましょう。",
whichWordCompletes: "どの単語が文を完成させますか？",
correctOrder: "正しい順番です。",
notQuiteTapBack: "おしい——タイルをタップして戻しましょう。",
notQuiteTryAgain: "おしい——もう一度。",
completedLabel: "完了",
notEnoughText: "このエクササイズに十分なテキストがありません。",
listenFirst: "まず聞く",
tapToSpeak: "タップして話し、終わったらもう一度タップ",
speakNowTapDone: "話してください——終わったらもう一度タップ",
scoringLabel: "採点中…",
playingAudio: "再生中…",
sentenceWord: "文",
textComplete: "テキスト完了",
nicelyDone: "よくできました！",
youSpokeAll: "すべての文を音読しました：",
sentencesOutLoud: "文",
overallLabel: "総合",
tapToRetrySentence: "文をタップしてもう一度練習",
pasteAnotherText: "別のテキストを貼り付け",
chooseFromLibrary: "ライブラリから選ぶ",
pasteYouTubeLink: "YouTubeのリンクを貼り付け…",
loadBtn: "読み込む",
pasteLinkAbove: "上にYouTubeのリンクを貼り付けてください",
loadingCaptions: "字幕を読み込み中…",
noCaptionsTitle: "字幕が見つかりません",
noCaptionsSub: "動画は開きましたが、学習中の言語の字幕が見つかりませんでした。",
tryAnotherVideo: "別の動画を試す",
captionsUnavailable: "字幕は一時的に利用できません",
tryAgain: "もう一度試す",
speakThisLine: "この行を発音",
translatePill: "翻訳",
pinyinPill: "ピンイン",
romajiPill: "ローマ字",
quotaChecksTitle: "本日の無料チェックを使い切りました",
quotaChecksSub: "本日の発音チェック{n}回をすべて使いました。Proなら毎日の上限なしで練習できます。",
quotaResetTomorrow: "無料チェックは明日リセットされます。",
quotaTextsTitle: "本日の無料テキストを使い切りました",
quotaTextsSub: "今日{n}件のテキストを追加しました。Proなら無制限です。",
quotaSavedSub: "{n}件のテキストを保存済み（無料上限）。Proなら無制限です。",
quotaLimitTitle: "無料プランの上限に達しました",
quotaDeckSub: "無料のデッキは{n}個まで。Proならデッキもカードも無制限です。",
quotaCardSub: "デッキに{n}枚のカード（無料上限）。Proなら無制限です。",
quotaVideoTitle: "動画はPro機能です",
quotaVideoSub: "お試し動画{n}本を使いました。Proならどの動画でも学べます。",
quotaTtsTitle: "本日の無料音声を使い切りました",
quotaTtsSub: "Proなら毎日の上限なしで聞き放題です。",
quotaTtsReset: "無料音声は明日リセットされます。",
quotaTransTitle: "本日の無料翻訳を使い切りました",
quotaTransSub: "Proなら毎日の上限なしで翻訳できます。",
quotaTransReset: "無料翻訳は明日リセットされます。",
upgradeDefaultTitle: "Proにアップグレード",
upgradeDefaultSub: "Proなら無制限に使えます。",
cmpTextsDay: "テキスト / 日",
cmpChecksDay: "発音チェック / 日",
cmpSavedTexts: "保存テキスト",
cmpDecksCards: "デッキ · カード",
cmpVideos: "字幕付き動画",
freeLabel: "無料",
proLabel: "Pro",
maybeLater: "また今度",
annualPlanBtn: "年額 — $49/年",
monthlyPlanBtn: "月額 — $6.99/月",
savePct: "41%お得",
freePlanLabel: "無料プラン",

saved: "保存しました",
savedTextsError: "保存されたテキストを読み込めませんでした。",
hidePinyin: "読み方を隠す",
voice: "音声",
voicePickerHeading: "この言語の音声を選択",
wordSaveHint: "ヒント：単語をクリックして聞き、翻訳し、単語カードに保存できます。",
hideFullText: "テキストを隠す",
showFullText: "テキストを表示",
grammarFailed: "文法チェックに失敗しました。",
pinyinError: "読み方を読み込めませんでした。"
}

};
